// apps/web-vue/src/components/Sales/SalesByDay.vue
<script setup lang="ts">
import { computed, ref } from "vue";

import { formatPrice } from "@livrelibre/shared/format";
import { PAYMENT_METHODS } from "@livrelibre/shared/sale";

import Card from "@/components/Card.vue";
import CardBody from "@/components/CardBody.vue";
import CardTitle from "@/components/CardTitle.vue";
import ErrorMessage from "@/components/ErrorMessage.vue";
import CategoriesTable from "@/components/PaymentStats/CategoriesTable.vue";
import CategorySkeleton from "@/components/PaymentStats/CategorySkeleton.vue";
import SalesSkeleton from "@/components/Sales/SalesSkeleton.vue";
import SalesTable from "@/components/Sales/SalesTable.vue";
import StatsByTVA from "@/components/TVAStats/StatsByTVA.vue";
import TVASkeleton from "@/components/TVAStats/TVASkeleton.vue";
import Title from "@/components/Title.vue";
import { useTRPCQuery } from "@/utils/query";
import { useScrollRestoration } from "@/utils/scroll";

const props = defineProps<{ date: string }>();

const root = ref<HTMLElement | null>(null);
useScrollRestoration(root);

const result = useTRPCQuery(
  "salesByDay",
  computed(() => props.date),
);

const formatDate = (date: string) => date.split("-").reverse().join("/");

const title = computed(() => `Liste des ventes du ${formatDate(props.date)}`);
const salesTitle = computed(() =>
  result.isPending.value
    ? `Ventes du ${props.date}`
    : `Ventes du ${formatDate(props.date)} (${String(result.data.value?.salesCount ?? 0)})`,
);
const categories = computed(() =>
  (result.data.value?.paymentMethods ?? []).map((method) => ({
    ...method,
    label: PAYMENT_METHODS[method.type],
  })),
);
</script>

<template>
  <div
    ref="root"
    class="flex flex-1 flex-col gap-lg max-h-full overflow-auto pr-1 pb-1 -mr-1 -mb-1"
  >
    <Title>{{ title }}</Title>
    <div class="flex gap-lg items-start flex-wrap">
      <Card class="flex-1">
        <CardTitle>Répartition par TVA</CardTitle>
        <CardBody>
          <ErrorMessage v-if="result.isError.value" />
          <TVASkeleton v-else-if="result.isPending.value" />
          <StatsByTVA v-else :stats="result.data.value?.tva ?? []" />
        </CardBody>
      </Card>
      <Card class="flex-1">
        <CardTitle>Répartition par type de paiement</CardTitle>
        <CardBody>
          <ErrorMessage v-if="result.isError.value" />
          <CategorySkeleton v-else-if="result.isPending.value" />
          <div v-else class="flex flex-1 flex-col gap-3">
            <CategoriesTable :categories="categories" />
            <p class="self-end">
              <strong>Total&nbsp;: </strong>
              <span class="font-number">
                {{ formatPrice(result.data.value?.total ?? 0) }}
              </span>
            </p>
          </div>
        </CardBody>
      </Card>
    </div>
    <Card class="flex flex-col">
      <CardTitle>{{ salesTitle }}</CardTitle>
      <CardBody>
        <ErrorMessage v-if="result.isError.value" />
        <SalesSkeleton v-else-if="result.isPending.value" />
        <SalesTable v-else :carts="result.data.value?.carts ?? []" />
      </CardBody>
    </Card>
  </div>
</template>

// apps/web/src/components/Sales/SalesByDay.tsx
import { type ReactElement, useRef } from "react";

import { formatPrice } from "@livrelibre/shared/format";
import { PAYMENT_METHODS } from "@livrelibre/shared/sale";

import { Card, CardBody, CardTitle } from "@/components/Card";
import { ErrorMessage } from "@/components/ErrorMessage";
import { CategoriesTable } from "@/components/PaymentStats/CategoriesTable";
import { CategorySkeleton } from "@/components/PaymentStats/CategorySkeleton";
import { StatsByTVA } from "@/components/TVAStats/StatsByTVA";
import { TVASkeleton } from "@/components/TVAStats/TVASkeleton";
import { Title } from "@/components/Title";
import { useScrollRestoration } from "@/utils/scroll";
import { trpc } from "@/utils/trpc";

import { SalesSkeleton } from "./SalesSkeleton";
import { SalesTable } from "./SalesTable";

const formatDate = (date: string) => date.split("-").reverse().join("/");

const TVALoader = ({ date }: { date: string }) => {
  const result = trpc.salesByDay.useQuery(date);
  if (result.isError) {
    return <ErrorMessage />;
  }
  if (result.isPending) {
    return <TVASkeleton />;
  }
  return <StatsByTVA stats={result.data.tva} />;
};

const CategoriesLoader = ({ date }: { date: string }) => {
  const result = trpc.salesByDay.useQuery(date);
  if (result.isError) {
    return <ErrorMessage />;
  }
  if (result.isPending) {
    return <CategorySkeleton />;
  }
  const categories = result.data.paymentMethods.map((m) => ({
    ...m,
    label: PAYMENT_METHODS[m.type],
  }));
  return (
    <div className="flex flex-1 flex-col gap-3">
      <CategoriesTable categories={categories} />
      <p className="self-end">
        <strong>Total&nbsp;: </strong>
        <span className="font-number">{formatPrice(result.data.total)}</span>
      </p>
    </div>
  );
};

const SalesLoader = ({ date }: { date: string }) => {
  const result = trpc.salesByDay.useQuery(date);
  if (result.isError) {
    return <ErrorMessage />;
  }
  if (result.isPending) {
    return (
      <Card className="flex flex-col">
        <CardTitle>{`Ventes du ${date}`}</CardTitle>
        <CardBody>
          <SalesSkeleton />
        </CardBody>
      </Card>
    );
  }
  return (
    <Card className="flex flex-col">
      <CardTitle>{`Ventes du ${formatDate(date)} (${result.data.salesCount})`}</CardTitle>
      <CardBody>
        <SalesTable carts={result.data.carts} />
      </CardBody>
    </Card>
  );
};

export const SalesByDay = ({ date }: { date: string }): ReactElement | null => {
  const ref = useRef<HTMLDivElement>(null);
  useScrollRestoration(ref);

  const title = `Liste des ventes du ${formatDate(date)}`;
  return (
    // padding is needed for shadow to be visible despite the overflow-auto
    <div
      ref={ref}
      className="flex flex-1 flex-col gap-lg max-h-full overflow-auto pr-1 pb-1 -mr-1 -mb-1"
    >
      <Title>{title}</Title>
      <div className="flex gap-lg items-start flex-wrap">
        <Card className="flex-1">
          <CardTitle>Répartition par TVA</CardTitle>
          <CardBody>
            <TVALoader date={date} />
          </CardBody>
        </Card>
        <Card className="flex-1">
          <CardTitle>Répartition par type de paiement</CardTitle>
          <CardBody>
            <CategoriesLoader date={date} />
          </CardBody>
        </Card>
      </div>
      <SalesLoader date={date} />
    </div>
  );
};
