// apps/web-vue/src/components/TVAStats/TVASkeleton.vue
<script setup lang="ts">
import Skeleton from "@/components/Skeleton.vue";
</script>

<template>
  <Skeleton :height="300">
    <template v-for="n in 9" :key="n">
      <rect
        x="5%"
        :y="(n - 1) * 30 + 15"
        rx="2"
        ry="2"
        width="19%"
        height="10"
      />
      <rect
        x="27%"
        :y="(n - 1) * 30 + 15"
        rx="2"
        ry="2"
        width="19%"
        height="10"
      />
      <rect
        x="49%"
        :y="(n - 1) * 30 + 15"
        rx="2"
        ry="2"
        width="19%"
        height="10"
      />
      <rect
        x="71%"
        :y="(n - 1) * 30 + 15"
        rx="2"
        ry="2"
        width="19%"
        height="10"
      />
    </template>
  </Skeleton>
</template>

// src/components/TVAStats/TVASkeleton.tsx
import ContentLoader from "react-content-loader";

const TVASkeletonRow = ({ n }: { n: number }) => (
  <>
    <rect x="5%" y={n * 30 + 15} rx="2" ry="2" width="19%" height="10" />
    <rect x="27%" y={n * 30 + 15} rx="2" ry="2" width="19%" height="10" />
    <rect x="49%" y={n * 30 + 15} rx="2" ry="2" width="19%" height="10" />
    <rect x="71%" y={n * 30 + 15} rx="2" ry="2" width="19%" height="10" />
  </>
);

export const TVASkeleton = (): JSX.Element => (
  <ContentLoader height={300} width="100%">
    {Array(9)
      .fill(0)
      .map((_, i) => (
        <TVASkeletonRow key={i} n={i} />
      ))}
  </ContentLoader>
);
