// src/components/Dashboard/Dashboard.tsx
import { Title } from "@/components/Title";

import { Bookmarks } from "./Bookmarks";
import { SellNewItem } from "./SellNewItem";

export const Dashboard = (): JSX.Element => {
  return (
    <div className="flex items-start gap-lg flex-1 flex-wrap">
      <Title>Tableau de bord</Title>
      <Bookmarks />
      <div className="flex flex-col gap-lg flex-1">
        <SellNewItem />
      </div>
    </div>
  );
};

// apps/web-vue/src/components/Dashboard/Dashboard.vue
<script setup lang="ts">
import Title from "@/components/Title.vue";

import Bookmarks from "./Bookmarks.vue";
import SellNewItem from "./SellNewItem.vue";
</script>

<template>
  <div class="flex items-start gap-lg flex-1 flex-wrap">
    <Title>Tableau de bord</Title>
    <Bookmarks />
    <div class="flex flex-col gap-lg flex-1">
      <SellNewItem />
    </div>
  </div>
</template>
