// apps/web/src/components/Dashboard/SellNewItem.tsx
import * as React from "react";
import { faCartPlus } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useForm } from "react-hook-form";

import type { NewCartItem } from "@livrelibre/server/server/cart";
import { formatTVA } from "@livrelibre/shared/format";
import { ITEM_TYPES, TVAValues } from "@livrelibre/shared/item";

import { Alert } from "@/components/Alert";
import { Button } from "@/components/Button";
import { Card, CardBody, CardTitle } from "@/components/Card";
import { Input, Select } from "@/components/FormControls";
import { FormRow } from "@/components/FormRow";
import { getErrorMessage } from "@/utils/errors";
import { trpc } from "@/utils/trpc";

type TAlert = {
  type: React.ComponentProps<typeof Alert>["type"];
  message: string;
};

export const SellNewItem = (): React.ReactElement => {
  const { register, handleSubmit, reset } = useForm<NewCartItem>();
  const utils = trpc.useUtils();
  const [alert, setAlert] = React.useState<TAlert | null>(null);
  const { mutateAsync, isPending } = trpc.addNewItemToCart.useMutation({
    meta: { errorToast: false },
    async onSuccess() {
      await utils.cart.invalidate();
    },
    onError(error) {
      setAlert({ type: "error", message: getErrorMessage(error) });
    },
  });
  const onSubmit = async (data: NewCartItem) => {
    try {
      await mutateAsync(data);
      reset();
      setAlert({ type: "success", message: "Article ajouté au panier" });
    } catch {
      // handled by onError
    }
  };

  return (
    <Card className="mb-lg">
      <CardTitle>Vendre un article non répertorié</CardTitle>
      <CardBody className="flex-col gap-4">
        <form
          className="flex flex-col flex-1"
          onSubmit={handleSubmit(onSubmit)}
        >
          <FormRow label="Prix">
            <Input
              type="number"
              {...register("price")}
              className="font-number"
              step={0.01}
              required
            />
          </FormRow>
          <FormRow label="Titre">
            <Input
              type="text"
              {...register("title")}
              placeholder="Article indépendant"
            />
          </FormRow>
          <FormRow label="Type">
            <Select {...register("type")} defaultValue="book">
              {Object.entries(ITEM_TYPES).map(([key, label]) => (
                <option value={key} key={key}>
                  {label}
                </option>
              ))}
            </Select>
          </FormRow>
          <FormRow label="TVA">
            <Select
              {...register("tva")}
              defaultValue="5.5"
              className="font-number"
            >
              {TVAValues.map((value) => (
                <option value={value} key={value}>
                  {formatTVA(value)}
                </option>
              ))}
            </Select>
          </FormRow>
          <Button type="submit" className="self-center" disabled={isPending}>
            <FontAwesomeIcon icon={faCartPlus} className="mr-sm" />
            Ajouter au panier
          </Button>
        </form>
        {alert ? (
          <Alert
            type={alert.type}
            onDismiss={() => {
              setAlert(null);
            }}
          >
            {alert.message}
          </Alert>
        ) : null}
      </CardBody>
    </Card>
  );
};

// apps/web-vue/src/components/Dashboard/SellNewItem.vue
<script setup lang="ts">
import { faCartPlus } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { ref } from "vue";

import { formatTVA } from "@livrelibre/shared/format";
import {
  ITEM_TYPES,
  type ItemType,
  type TVA,
  TVAValues,
} from "@livrelibre/shared/item";

import Alert from "@/components/Alert.vue";
import Button from "@/components/Button.vue";
import Card from "@/components/Card.vue";
import CardBody from "@/components/CardBody.vue";
import CardTitle from "@/components/CardTitle.vue";
import FormRow from "@/components/FormRow.vue";
import Input from "@/components/Input.vue";
import Select from "@/components/Select.vue";
import { getErrorMessage } from "@/utils/errors";
import { useTRPCMutation, useTRPCUtils } from "@/utils/query";

type TAlert = {
  type: "success" | "error";
  message: string;
};

const utils = useTRPCUtils();
const price = ref<string | number>("");
const title = ref("");
const type = ref<ItemType>("book");
const tva = ref<TVA>("5.5");
const alert = ref<TAlert | null>(null);

const mutation = useTRPCMutation("addNewItemToCart", {
  meta: { errorToast: false },
  async onSuccess() {
    await utils.invalidate("cart");
  },
  onError(error) {
    alert.value = { type: "error", message: getErrorMessage(error) };
  },
});

const onSubmit = async () => {
  try {
    await mutation.mutateAsync({
      price: String(price.value),
      title: title.value,
      type: type.value,
      tva: tva.value,
    });
    price.value = "";
    title.value = "";
    type.value = "book";
    tva.value = "5.5";
    alert.value = { type: "success", message: "Article ajouté au panier" };
  } catch {
    // handled by onError
  }
};
</script>

<template>
  <Card class="mb-lg">
    <CardTitle>Vendre un article non répertorié</CardTitle>
    <CardBody class="flex-col gap-4">
      <form class="flex flex-col flex-1" @submit.prevent="onSubmit">
        <FormRow label="Prix">
          <Input
            v-model="price"
            type="number"
            class="font-number"
            :step="0.01"
            required
          />
        </FormRow>
        <FormRow label="Titre">
          <Input
            v-model="title"
            type="text"
            placeholder="Article indépendant"
          />
        </FormRow>
        <FormRow label="Type">
          <Select v-model="type">
            <option
              v-for="[key, label] in Object.entries(ITEM_TYPES)"
              :key="key"
              :value="key"
            >
              {{ label }}
            </option>
          </Select>
        </FormRow>
        <FormRow label="TVA">
          <Select v-model="tva" class="font-number">
            <option v-for="value in TVAValues" :key="value" :value="value">
              {{ formatTVA(value) }}
            </option>
          </Select>
        </FormRow>
        <Button
          type="submit"
          class="self-center"
          :disabled="mutation.isPending.value"
        >
          <FontAwesomeIcon :icon="faCartPlus" class="mr-sm" />
          Ajouter au panier
        </Button>
      </form>
      <Alert v-if="alert" :type="alert.type" @dismiss="alert = null">
        {{ alert.message }}
      </Alert>
    </CardBody>
  </Card>
</template>
