// apps/web-vue/src/pages/order/[orderId].vue
<script setup lang="ts">
import {
  faCheckCircle,
  faTimesCircle,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { computed } from "vue";
import { ContentLoader } from "vue-content-loader";
import { useRoute, useRouter } from "vue-router";
import { toast } from "vue-sonner";

import type { RawOrder } from "@livrelibre/shared/order";

import Button from "@/components/Button.vue";
import Card from "@/components/Card.vue";
import CardBody from "@/components/CardBody.vue";
import CardTitle from "@/components/CardTitle.vue";
import ConfirmationDialog from "@/components/ConfirmationDialog.vue";
import ErrorMessage from "@/components/ErrorMessage.vue";
import LinkButton from "@/components/LinkButton.vue";
import NoResults from "@/components/NoResults.vue";
import OrderForm from "@/components/OrderForm.vue";
import Title from "@/components/Title.vue";
import type { OrderFormData } from "@/components/orderForm";
import { getErrorMessage } from "@/utils/errors";
import { useTRPCMutation, useTRPCQuery, useTRPCUtils } from "@/utils/query";
import { useQueryParams } from "@/utils/useQueryParams";

const CARD_TITLE = "Modifier une commande";

const route = useRoute();
const router = useRouter();
const utils = useTRPCUtils();
const { query } = useQueryParams();
const id = computed(() => Number(route.params.orderId));

const orderQuery = useTRPCQuery("order", id);

const mutation = useTRPCMutation("updateOrder", {
  meta: { errorToast: false },
  onSuccess(data) {
    if (data.type === "success") {
      void utils.invalidate("order", id.value);
      toast.success(data.msg);
      void router.push({ path: "/orders", query: query.value });
    } else {
      toast.error(data.msg);
    }
  },
  onError(error) {
    toast.error(getErrorMessage(error));
  },
});

const deleteMutation = useTRPCMutation("deleteOrder", {
  meta: { errorToast: false },
});

const submit = async (order: RawOrder) =>
  await mutation.mutateAsync({ order, id: id.value });

const deleteOrder = async () => {
  try {
    const res = await deleteMutation.mutateAsync({ id: id.value });
    if (res.type === "success") {
      toast.success(res.msg);
      await router.push({ path: "/orders", query: query.value });
    } else {
      toast.error(res.msg);
    }
  } catch (error) {
    toast.error(getErrorMessage(error));
  }
};

const data = computed<OrderFormData | undefined>(() => {
  const order = orderQuery.data.value;
  if (!order) return undefined;
  return { ...order, created: new Date(order.created) };
});
</script>

<template>
  <div class="flex-1 max-w-6xl mx-auto">
    <Title>Modifier une commande</Title>
    <Card v-if="orderQuery.isError.value">
      <CardTitle>{{ CARD_TITLE }}</CardTitle>
      <CardBody>
        <ErrorMessage />
      </CardBody>
    </Card>
    <Card v-else-if="orderQuery.isPending.value">
      <CardTitle>{{ CARD_TITLE }}</CardTitle>
      <CardBody>
        <ContentLoader :height="300" width="100%">
          <template v-for="n in 4" :key="n">
            <rect
              x="5%"
              :y="(n - 1) * 50"
              rx="2"
              ry="2"
              width="12%"
              height="30"
            />
            <rect
              x="20%"
              :y="(n - 1) * 50"
              rx="2"
              ry="2"
              width="30%"
              height="30"
            />
          </template>
        </ContentLoader>
      </CardBody>
    </Card>
    <Card v-else-if="orderQuery.data.value == null">
      <CardTitle>Commande introuvable</CardTitle>
      <CardBody>
        <NoResults />
      </CardBody>
    </Card>
    <OrderForm
      v-else-if="data"
      :title="CARD_TITLE"
      :on-submit="submit"
      :data="data"
    >
      <ConfirmationDialog
        title="Supprimer une commande"
        message="Êtes-vous sûr⋅e de vouloir supprimer cette commande ? Cette action ne peut pas être annulée."
        @confirm="deleteOrder"
      />
      <LinkButton
        :to="{ path: '/orders', query: query }"
        class="mr-2 px-md !bg-[#6E6E6E]"
      >
        <FontAwesomeIcon :icon="faTimesCircle" class="mr-sm" />
        Annuler
      </LinkButton>
      <Button type="submit" class="px-md" :disabled="mutation.isPending.value">
        <FontAwesomeIcon :icon="faCheckCircle" class="mr-sm" />
        Modifier
      </Button>
    </OrderForm>
  </div>
</template>

// src/pages/order/[orderId].tsx
import * as React from "react";
import {
  faCheckCircle,
  faTimesCircle,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { type NextRouter, useRouter } from "next/router";
import ContentLoader from "react-content-loader";
import { toast } from "react-toastify";

import { Button, LinkButton } from "@/components/Button";
import { Card, CardBody, CardTitle } from "@/components/Card";
import { ConfirmationDialog } from "@/components/ConfirmationDialog";
import { ErrorMessage } from "@/components/ErrorMessage";
import { OrderForm } from "@/components/OrderForm";
import { Title } from "@/components/Title";
import { type RawOrder, deserializeOrder } from "@livrelibre/shared/order";
import { trpc } from "@/utils/trpc";

const CARD_TITLE = "Modifier une commande";

const SkeletonRow = ({ n }: { n: number }) => (
  <>
    <rect x="5%" y={n * 50} rx="2" ry="2" width="12%" height="30" />
    <rect x="20%" y={n * 50} rx="2" ry="2" width="30%" height="30" />
  </>
);

const OrderFormSkeleton = (): React.ReactElement => (
  <ContentLoader height={300} width="100%">
    {Array(4)
      .fill(0)
      .map((_, i) => (
        <SkeletonRow key={i} n={i} />
      ))}
  </ContentLoader>
);

const getOrdersURL = (router: NextRouter) => {
  const { orderId, ...query } = router.query;
  return { pathname: "/orders", query };
};

const DeleteOrder = ({ id }: { id: number }) => {
  const router = useRouter();
  const deleteMutation = trpc.deleteOrder.useMutation();
  const deleteOrder = async () => {
    const res = await deleteMutation.mutateAsync({ id });
    if (res.type === "success") {
      toast.success(res.msg);
      await router.push(getOrdersURL(router));
    } else {
      toast.error(res.msg);
    }
  };

  return (
    <ConfirmationDialog
      title="Supprimer une commande"
      message="Êtes-vous sûr⋅e de vouloir supprimer cette commande ? Cette action ne peut pas être annulée."
      onConfirm={deleteOrder}
    />
  );
};

const OrderLoader = ({ id }: { id: number }) => {
  const result = trpc.order.useQuery(id);
  const utils = trpc.useUtils();
  const router = useRouter();
  const mutation = trpc.updateOrder.useMutation({
    async onSuccess(data) {
      if (data.type === "success") {
        await utils.order.invalidate();
        toast.success(data.msg);
        void router.push(getOrdersURL(router));
      } else {
        toast.error(data.msg);
      }
    },
  });

  const submit = async (order: RawOrder) => {
    return await mutation.mutateAsync({ order, id });
  };

  if (result.status === "error") {
    return (
      <Card>
        <CardTitle>{CARD_TITLE}</CardTitle>
        <CardBody>
          <ErrorMessage />
        </CardBody>
      </Card>
    );
  }

  if (result.data == null) {
    return (
      <Card>
        <CardTitle>{CARD_TITLE}</CardTitle>
        <CardBody>
          <OrderFormSkeleton />
        </CardBody>
      </Card>
    );
  }

  return (
    <OrderForm
      title={CARD_TITLE}
      onSubmit={submit}
      data={{
        ...deserializeOrder(result.data),
      }}
      formId="orderForm"
    >
      <DeleteOrder id={id} />
      <LinkButton
        href={getOrdersURL(router)}
        className="mr-2 px-md !bg-[#6E6E6E]"
      >
        <FontAwesomeIcon icon={faTimesCircle} className="mr-sm" />
        Annuler
      </LinkButton>
      <Button
        type="submit"
        className="px-md"
        form="orderForm"
        disabled={mutation.isPending}
      >
        <FontAwesomeIcon icon={faCheckCircle} className="mr-sm" />
        Modifier
      </Button>
    </OrderForm>
  );
};

const UpdateOrder = () => {
  const router = useRouter();
  const { orderId } = router.query;
  if (typeof orderId !== "string") {
    return null;
  }
  return (
    <div className="flex-1 max-w-6xl mx-auto">
      <Title>Modifier une commande</Title>
      <OrderLoader id={Number(orderId)} />
    </div>
  );
};

export default UpdateOrder;
