// apps/web-vue/src/pages/order/new.vue
<script setup lang="ts">
import { faPlus } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { computed } from "vue";
import { useRoute, useRouter } from "vue-router";
import { toast } from "vue-sonner";

import type { RawOrder } from "@livrelibre/shared/order";

import Button from "@/components/Button.vue";
import ErrorMessage from "@/components/ErrorMessage.vue";
import OrderForm from "@/components/OrderForm.vue";
import Title from "@/components/Title.vue";
import type { OrderFormData } from "@/components/orderForm";
import { getErrorMessage } from "@/utils/errors";
import { useTRPCMutation, useTRPCQuery } from "@/utils/query";

const route = useRoute();
const router = useRouter();

const rawId = route.query.item;
const itemIdStr = typeof rawId === "string" ? rawId : "";

const itemQuery = useTRPCQuery(
  "searchItem",
  computed(() => Number(itemIdStr)),
  computed(() => ({ enabled: itemIdStr !== "" })),
);

const mutation = useTRPCMutation("newOrder", {
  meta: { errorToast: false },
  onSuccess(data) {
    if (data.type === "success") {
      toast.success(data.msg);
      void router.push("/orders");
    } else {
      toast.error(data.msg);
    }
  },
  onError(error) {
    toast.error(getErrorMessage(error));
  },
});

const submit = async (order: RawOrder) => await mutation.mutateAsync(order);

const data = computed<OrderFormData>(() => ({
  item: itemQuery.data.value || null,
  nb: 1,
  created: new Date(),
}));
</script>

<template>
  <div class="flex-1 max-w-6xl mx-auto">
    <Title>Nouvelle commande</Title>
    <ErrorMessage v-if="itemQuery.isError.value" />
    <div v-else-if="itemQuery.isPending.value && itemIdStr">Chargement…</div>
    <OrderForm
      v-else
      title="Nouvelle commande"
      :on-submit="submit"
      :data="data"
    >
      <Button type="submit" class="px-md" :disabled="mutation.isPending.value">
        <FontAwesomeIcon :icon="faPlus" class="mr-sm" />
        Ajouter
      </Button>
    </OrderForm>
  </div>
</template>

// src/pages/order/new.tsx
import * as React from "react";
import { faPlus } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useRouter } from "next/router";
import { toast } from "react-toastify";

import { Button } from "@/components/Button";
import { ErrorMessage } from "@/components/ErrorMessage";
import { OrderForm } from "@/components/OrderForm";
import { Title } from "@/components/Title";
import type { RawOrder } from "@/utils/order";
import { trpc } from "@/utils/trpc";

const OrderBody = () => {
  const router = useRouter();
  const rawId = router.query.item;
  const id = typeof rawId === "string" ? rawId : "";
  const result = trpc.searchItem.useQuery(Number(id), { enabled: id !== "" });
  const mutation = trpc.newOrder.useMutation({
    onSuccess(data) {
      if (data.type === "success") {
        toast.success(data.msg);
        void router.push("/orders");
      } else {
        toast.error(data.msg);
      }
    },
    onError() {
      toast.error("Impossible d'ajouter la commande");
    },
  });

  const submit = async (order: RawOrder) => {
    return await mutation.mutateAsync(order);
  };
  if (result.status === "error") {
    return <ErrorMessage />;
  }
  if (result.status === "loading" && id) {
    return <div>Chargement…</div>;
  }
  const data: React.ComponentProps<typeof OrderForm>["data"] = {
    item: result.data || null,
    nb: 1,
    created: new Date(),
  };
  return (
    <OrderForm title="Nouvelle commande" onSubmit={submit} data={data}>
      <Button type="submit" className="px-md">
        <FontAwesomeIcon icon={faPlus} className="mr-sm" />
        Ajouter
      </Button>
    </OrderForm>
  );
};

const NewOrder = (): React.ReactElement => {
  return (
    <div className="flex-1 max-w-6xl mx-auto">
      <Title>Nouvelle commande</Title>
      <OrderBody />
    </div>
  );
};

export default NewOrder;
