// apps/web/src/pages/customer/new.tsx
import * as React from "react";
import { faPlus, faTimesCircle } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

import { Button, LinkButton } from "@/components/Button";
import {
  CustomerForm,
  type CustomerFormFields,
} from "@/components/CustomerForm";
import { Title } from "@/components/Title";
import { trpc } from "@/utils/trpc";

const NewCustomer = (): React.ReactElement => {
  const mutation = trpc.updateCustomer.useMutation({
    meta: { errorToast: false },
  });
  const submit = async (customer: CustomerFormFields) => {
    return await mutation.mutateAsync({ customer });
  };
  return (
    <div className="[margin-left:10%] [margin-right:10%] flex-1">
      <Title>Ajouter un client</Title>
      <CustomerForm title="Ajouter un client" onSubmit={submit}>
        <LinkButton to="/customers" className="mr-2 px-md !bg-[#6E6E6E]">
          <FontAwesomeIcon icon={faTimesCircle} className="mr-sm" />
          Annuler
        </LinkButton>
        <Button type="submit" className="px-md" disabled={mutation.isPending}>
          <FontAwesomeIcon icon={faPlus} className="mr-sm" />
          Ajouter
        </Button>
      </CustomerForm>
    </div>
  );
};

export default NewCustomer;

// apps/web-vue/src/pages/customer/new.vue
<script setup lang="ts">
import { faPlus, faTimesCircle } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

import Button from "@/components/Button.vue";
import CustomerForm from "@/components/CustomerForm.vue";
import LinkButton from "@/components/LinkButton.vue";
import Title from "@/components/Title.vue";
import type { CustomerFormFields } from "@/components/customerForm";
import { useTRPCMutation } from "@/utils/query";

const mutation = useTRPCMutation("updateCustomer", {
  meta: { errorToast: false },
});

const submit = async (customer: CustomerFormFields) =>
  await mutation.mutateAsync({ customer });
</script>

<template>
  <div class="[margin-left:10%] [margin-right:10%] flex-1">
    <Title>Ajouter un client</Title>
    <CustomerForm title="Ajouter un client" :on-submit="submit">
      <LinkButton to="/customers" class="mr-2 px-md !bg-[#6E6E6E]">
        <FontAwesomeIcon :icon="faTimesCircle" class="mr-sm" />
        Annuler
      </LinkButton>
      <Button type="submit" class="px-md" :disabled="mutation.isPending.value">
        <FontAwesomeIcon :icon="faPlus" class="mr-sm" />
        Ajouter
      </Button>
    </CustomerForm>
  </div>
</template>
