// apps/web/src/components/CustomerForm.tsx
import * as React from "react";
import { useForm } from "react-hook-form";

import type { Customer } from "@livrelibre/shared/customer";

import { Alert } from "@/components/Alert";
import { Card, CardBody, CardFooter, CardTitle } from "@/components/Card";
import { Input, Textarea } from "@/components/FormControls";
import { FormRow } from "@/components/FormRow";
import { getErrorMessage } from "@/utils/errors";

export type CustomerFormFields = Omit<Customer, "purchases">;

type TAlert = {
  type: React.ComponentProps<typeof Alert>["type"];
  message: string;
};

export const CustomerForm = ({
  title,
  onSubmit,
  data,
  children,
  onSuccess,
}: {
  title: string;
  onSubmit: (
    data: CustomerFormFields,
  ) => Promise<{ type: "error" | "success"; msg: string }>;
  data?: CustomerFormFields;
  onSuccess?: () => void;
  children: React.ReactNode;
}): React.ReactElement => {
  const { register, handleSubmit, reset } = useForm<CustomerFormFields>({
    defaultValues: data || {},
  });
  const [alert, setAlert] = React.useState<TAlert | null>(null);

  const submit = async (data: CustomerFormFields) => {
    try {
      const { type, msg: message } = await onSubmit(data);
      setAlert({ type, message });
      if (type === "success") {
        if (onSuccess) {
          onSuccess();
        } else {
          reset();
        }
      }
    } catch (error) {
      setAlert({ type: "error", message: getErrorMessage(error) });
    }
  };

  return (
    <Card className="max-h-full flex flex-col">
      <CardTitle>{title}</CardTitle>
      <form
        className="flex-1 flex flex-col h-0"
        onSubmit={handleSubmit(submit)}
      >
        <CardBody className="flex-col gap-5">
          <div className="flex flex-wrap flex-col">
            <FormRow label="Nom complet">
              <Input type="text" {...register("fullname")} required />
            </FormRow>
            <FormRow label="Téléphone">
              <Input type="tel" {...register("phone")} />
            </FormRow>
            <FormRow label="Email">
              <Input type="email" {...register("email")} />
            </FormRow>
            <FormRow label="Remarque contact">
              <Input type="text" {...register("contact")} />
            </FormRow>
            <FormRow label="Commentaires">
              <Textarea {...register("comment")} />
            </FormRow>
          </div>
        </CardBody>
        <CardFooter>
          <div className="flex justify-end mb-sm">{children}</div>
          {alert ? (
            <Alert
              type={alert.type}
              onDismiss={() => {
                setAlert(null);
              }}
            >
              {alert.message}
            </Alert>
          ) : null}
        </CardFooter>
      </form>
    </Card>
  );
};

// apps/web/src/components/CustomerForm.vue
<script setup lang="ts">
import { ref } from "vue";

import AppAlert from "@/components/AppAlert.vue";
import AppCard from "@/components/AppCard.vue";
import AppInput from "@/components/AppInput.vue";
import AppTextarea from "@/components/AppTextarea.vue";
import CardBody from "@/components/CardBody.vue";
import CardFooter from "@/components/CardFooter.vue";
import CardTitle from "@/components/CardTitle.vue";
import FormRow from "@/components/FormRow.vue";
import { getErrorMessage } from "@/utils/errors";

import type { CustomerFormFields, CustomerFormResult } from "./customerForm";
import type { AlertMessage } from "./form";

const props = defineProps<{
  title: string;
  data?: CustomerFormFields | undefined;
  onSubmit: (data: CustomerFormFields) => Promise<CustomerFormResult>;
}>();

const fullname = ref(props.data?.fullname ?? "");
const phone = ref(props.data?.phone ?? "");
const email = ref(props.data?.email ?? "");
const contact = ref(props.data?.contact ?? "");
const comment = ref(props.data?.comment ?? "");
const alert = ref<AlertMessage | null>(null);

const buildPayload = (): CustomerFormFields => ({
  fullname: fullname.value,
  phone: phone.value || null,
  email: email.value || null,
  contact: contact.value,
  comment: comment.value,
});

const reset = () => {
  fullname.value = "";
  phone.value = "";
  email.value = "";
  contact.value = "";
  comment.value = "";
};

const submit = async () => {
  try {
    const { type, msg: message } = await props.onSubmit(buildPayload());
    alert.value = { type, message };
    if (type === "success" && props.data === undefined) {
      reset();
    }
  } catch (error) {
    alert.value = { type: "error", message: getErrorMessage(error) };
  }
};
</script>

<template>
  <AppCard class="max-h-full flex flex-col">
    <CardTitle :level="1">{{ props.title }}</CardTitle>
    <form class="flex-1 flex flex-col h-0" @submit.prevent="submit">
      <CardBody class="flex-col gap-5">
        <div class="flex flex-wrap flex-col">
          <FormRow label="Nom complet">
            <AppInput v-model="fullname" type="text" required />
          </FormRow>
          <FormRow label="Téléphone">
            <AppInput v-model="phone" type="tel" />
          </FormRow>
          <FormRow label="Email">
            <AppInput v-model="email" type="email" />
          </FormRow>
          <FormRow label="Remarque contact">
            <AppInput v-model="contact" type="text" />
          </FormRow>
          <FormRow label="Commentaires">
            <AppTextarea v-model="comment" />
          </FormRow>
        </div>
      </CardBody>
      <CardFooter>
        <div class="flex justify-end mb-sm">
          <slot />
        </div>
        <AppAlert v-if="alert" :type="alert.type" @dismiss="alert = null">
          {{ alert.message }}
        </AppAlert>
      </CardFooter>
    </form>
  </AppCard>
</template>
