// src/components/FormRow.tsx
import clsx from "clsx";
import type { ReactElement } from "react";

type FormRowProps = {
  label: string;
  children: React.ReactNode;
  className?: string;
  fieldClass?: string;
};
export const FormRow = ({
  label,
  children,
  fieldClass,
}: FormRowProps): ReactElement => (
  <label className="flex cursor-pointer mb-md items-center">
    <span className="text-right mr-lg font-medium w-1/4 flex-shrink-0 whitespace-nowrap">
      {label}
    </span>
    <div className={clsx("flex w-2/3", fieldClass)}>{children}</div>
  </label>
);

// apps/web/src/components/FormRow.vue
<script setup lang="ts">
import { clsx } from "clsx";
import { useId } from "vue";

const props = defineProps<{
  label: string;
  fieldClass?: string;
  group?: boolean;
}>();

const labelId = useId();
</script>

<template>
  <div
    v-if="props.group"
    role="group"
    :aria-labelledby="labelId"
    class="flex mb-md items-center"
  >
    <span
      :id="labelId"
      class="text-right mr-lg font-medium w-1/4 shrink-0 whitespace-nowrap"
    >
      {{ props.label }}
    </span>
    <div :class="clsx('flex w-2/3', props.fieldClass)">
      <slot />
    </div>
  </div>
  <label v-else class="flex cursor-pointer mb-md items-center">
    <span class="text-right mr-lg font-medium w-1/4 shrink-0 whitespace-nowrap">
      {{ props.label }}
    </span>
    <div :class="clsx('flex w-2/3', props.fieldClass)">
      <slot />
    </div>
  </label>
</template>
