// src/components/ItemsCard.tsx
import React from "react";

import { Card, CardBody, CardTitle } from "@/components/Card";

export const ItemsCard = ({
  title,
  subtitle,
  children,
}: {
  title: string;
  children: React.ReactNode;
  subtitle?: React.ReactNode;
}) => (
  <Card className="max-h-full overflow-hidden flex flex-col">
    <CardTitle>{title}</CardTitle>
    {subtitle}
    <CardBody>{children}</CardBody>
  </Card>
);

// apps/web-vue/src/components/ItemsCard.vue
<script setup lang="ts">
import Card from "./Card.vue";
import CardBody from "./CardBody.vue";
import CardTitle from "./CardTitle.vue";

const props = defineProps<{ title: string }>();
</script>

<template>
  <Card class="max-h-full overflow-hidden flex flex-col">
    <CardTitle>{{ props.title }}</CardTitle>
    <slot name="subtitle" />
    <CardBody>
      <slot />
    </CardBody>
  </Card>
</template>
