// apps/web/src/components/OrderForm.tsx
import * as React from "react";
import {
  faAt,
  faCheckCircle,
  faPhone,
  faTimesCircle,
  faUserPlus,
  faWalking,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import clsx from "clsx";
import { useForm, useWatch } from "react-hook-form";
import { toast } from "react-toastify";

import type { Customer } from "@livrelibre/shared/customer";
import { toInputDate } from "@livrelibre/shared/date";
import type { Item } from "@livrelibre/shared/item";
import {
  type ContactMean,
  type RawOrder,
  STATUS_LABEL,
} from "@livrelibre/shared/order";

import { Button } from "@/components/Button";
import { Card, CardBody, CardFooter, CardTitle } from "@/components/Card";
import type { CustomerFormFields } from "@/components/CustomerForm";
import { Input, Select, Textarea } from "@/components/FormControls";
import { FormRow } from "@/components/FormRow";
import { SelectCustomer } from "@/components/SelectCustomer";
import { type NewItem, SelectItem } from "@/components/SelectItem";
import { trpc } from "@/utils/trpc";

const ContactMean = React.forwardRef<
  HTMLInputElement,
  React.PropsWithChildren<
    React.JSX.IntrinsicElements["input"] & {
      mean: ContactMean;
      isActive: boolean;
    }
  >
>(function ContactMean(props, ref) {
  const { mean, isActive, children, ...rest } = props;
  return (
    <>
      <input
        id={"radio-" + mean}
        type="radio"
        ref={ref}
        {...rest}
        value={mean}
        className="hidden"
      />
      <label
        htmlFor={"radio-" + mean}
        className={clsx(
          "rounded px-3 py-2 fault focus:outline-none border-2 cursor-pointer",
          "[transition:border-color_ease-in-out_0.15s]",
          { grow: mean === "mail" },
          { "basis-40": mean === "phone" },
          isActive ? "border-primary" : "[border-color:#ccc]",
        )}
      >
        {children}
      </label>
    </>
  );
});

const CustomerFormBody = (props: {
  hide: () => void;
  onAdd: (customer: Customer) => void;
  className?: string;
}) => {
  const { register, handleSubmit, formState } = useForm<CustomerFormFields>();
  const mutation = trpc.updateCustomer.useMutation();
  const submit = async (customer: CustomerFormFields) => {
    const resp = await mutation.mutateAsync({ customer });
    if (resp.type === "success") {
      toast.success(resp.msg);
      props.onAdd({ ...customer, id: resp.id });
      props.hide();
    } else {
      toast.error(resp.msg);
    }
  };
  return (
    <form
      onSubmit={handleSubmit(submit)}
      className={clsx(
        "transition-maxHeight duration-200 overflow-hidden",
        props.className,
      )}
    >
      <FormRow label="Nom complet">
        <Input type="text" {...register("fullname")} required />
      </FormRow>
      <FormRow label="Téléphone">
        <Input type="tel" {...register("phone")} />
      </FormRow>
      <FormRow label="Email">
        <Input type="email" {...register("email")} />
      </FormRow>
      <FormRow label="Remarque contact">
        <Input type="text" {...register("contact")} />
      </FormRow>
      <FormRow label="Commentaires">
        <Textarea {...register("comment")} />
      </FormRow>
      <div className="flex justify-end mb-4 mr-20">
        <Button
          type="button"
          className="px-md mr-4 !bg-[#6E6E6E]"
          onClick={props.hide}
        >
          <FontAwesomeIcon icon={faTimesCircle} className="mr-sm" />
          Annuler
        </Button>
        <Button
          type="submit"
          className="px-md"
          disabled={formState.isSubmitting}
        >
          <FontAwesomeIcon icon={faCheckCircle} className="mr-sm" />
          Ajouter
        </Button>
      </div>
    </form>
  );
};

type InputOrder = Omit<RawOrder, "customerId"> & {
  isbn: string | undefined;
  customerId: number | null;
};
type OrderData = Partial<Omit<RawOrder, "created">> & {
  created: Date;
  customer?: Customer;
  item?: Item | null;
};

export const OrderForm = ({
  title,
  onSubmit,
  data,
  children,
  formId,
}: {
  title: string;
  onSubmit: (
    data: RawOrder,
  ) => Promise<{ type: "error" | "success"; msg: string }>;
  data: OrderData;
  formId: string;
  children: React.ReactNode;
}): React.ReactElement => {
  const defaultValues = {
    ...data,
    created: toInputDate(data.created),
    isbn: data.item?.isbn,
    contact: data.contact ?? "unknown",
  };
  const { register, handleSubmit, reset, setValue, control } =
    useForm<InputOrder>({
      defaultValues,
      shouldUseNativeValidation: true,
    });
  const [customer, setCustomer] = React.useState<Customer | null>(
    data.customer ?? null,
  );
  const [item, setItem] = React.useState<Item | NewItem | null | undefined>(
    data.item ?? { id: null, title: data.itemTitle ?? "" },
  );
  const [showCustomerForm, setShowCustomerForm] = React.useState(false);
  const utils = trpc.useUtils();
  const contact = useWatch({ control, name: "contact" });
  const paid = useWatch({ control, name: "paid" });

  const toggleCustomerForm = () => {
    setShowCustomerForm((show) => !show);
  };

  const submit = async (order: InputOrder) => {
    if (order.isbn && !order.itemId) {
      const result = await utils.isbnSearch.fetch(order.isbn);
      if (result.count === 0) {
        toast.info("Aucun article trouvé pour cet ISBN");
      }
      updateItem(result.items[0]);
      return;
    }
    if (!order.customerId) {
      toast.info("Merci de sélectionner un⋅e client⋅e");
      return;
    }
    if (!order.itemTitle) {
      toast.info("Merci de renseigner le titre ou l'ISBN de l'article");
      return;
    }
    // Convert timezoned date to UTC date to avoid mismatch with server time
    order.created = new Date(order.created).toISOString();
    const { type } = await onSubmit({ ...order, customerId: order.customerId });
    if (type !== "success") {
      reset();
    }
  };

  const updateCustomer = (customer: Customer | null) => {
    setCustomer(customer);
    setValue("customerId", customer?.id ?? null);
  };

  const updateItem = (item: Item | NewItem | null | undefined) => {
    setItem(item);
    setValue("itemId", item?.id ?? null);
    setValue("itemTitle", item?.title ?? "");
    setValue("isbn", item && "isbn" in item ? item.isbn : "");
  };

  return (
    <Card className="max-h-full flex flex-col">
      <CardTitle>{title}</CardTitle>
      <form id={formId} onSubmit={handleSubmit(submit)} />
      <CardBody className="flex-col gap-5">
        <div className="flex flex-col">
          <FormRow label="Client⋅e">
            {showCustomerForm ? (
              <Input
                type="text"
                className="w-full bg-[#ccc] cursor-not-allowed"
                disabled
                value="Nouveau client"
              />
            ) : (
              <SelectCustomer
                customer={customer}
                setCustomer={updateCustomer}
                fullWidth
                required
              />
            )}
            <Button
              className="ml-sm self-center"
              title="Nouveau client"
              type="button"
              onClick={toggleCustomerForm}
            >
              <FontAwesomeIcon icon={faUserPlus} />
            </Button>
          </FormRow>
          <CustomerFormBody
            hide={toggleCustomerForm}
            onAdd={updateCustomer}
            className={showCustomerForm ? "max-h-[500px]" : "max-h-0"}
          />
          <FormRow label="Contacter par" fieldClass="gap-2">
            <ContactMean
              mean="unknown"
              isActive={contact === "unknown"}
              {...register("contact")}
            >
              Non renseigné
            </ContactMean>
            <ContactMean
              mean="in person"
              isActive={contact === "in person"}
              {...register("contact")}
            >
              <FontAwesomeIcon icon={faWalking} className="mr-1" />
              Passera
            </ContactMean>
            <ContactMean
              mean="phone"
              isActive={contact === "phone"}
              {...register("contact")}
            >
              <FontAwesomeIcon icon={faPhone} className="mr-1" />
              <em>{customer?.phone}</em>
            </ContactMean>
            <ContactMean
              mean="mail"
              isActive={contact === "mail"}
              {...register("contact")}
            >
              <FontAwesomeIcon icon={faAt} className="mr-1" />
              <em>{customer?.email}</em>
            </ContactMean>
          </FormRow>
          <FormRow label="Date">
            <Input type="datetime-local" {...register("created")} />
          </FormRow>
          <FormRow label="ISBN">
            <Input
              {...register("isbn", {
                validate: (isbn: string | undefined) =>
                  !isbn || /^\d{10,13}$/.test(isbn) || "ISBN invalide",
              })}
            />
          </FormRow>
          <FormRow label="Titre">
            <SelectItem item={item} setItem={updateItem} fullWidth />
          </FormRow>
          <FormRow label="Commentaires">
            <Textarea {...register("comment")} />
          </FormRow>
          <FormRow label="Nb d'exemplaires">
            <Input
              type="number"
              min="1"
              required
              {...register("nb", { valueAsNumber: true })}
            />
          </FormRow>
          <FormRow label="État">
            <Select {...register("ordered")} defaultValue="new">
              {Object.entries(STATUS_LABEL).map(([key, label]) => (
                <option value={key} key={key}>
                  {label}
                </option>
              ))}
            </Select>
          </FormRow>
          <FormRow
            label="Payé"
            fieldClass={
              paid
                ? "border-r-8 border-[rgba(245,0,0,0.5)] pr-2 min-h-6 w-fit"
                : ""
            }
          >
            <input type="checkbox" {...register("paid")} />
          </FormRow>
          <FormRow label="Client⋅e informé⋅e">
            <input type="checkbox" {...register("customerNotified")} />
          </FormRow>
        </div>
      </CardBody>
      <CardFooter>
        <div className="flex justify-end mb-sm">{children}</div>
      </CardFooter>
    </Card>
  );
};

// apps/web-vue/src/components/OrderForm.vue
<script setup lang="ts">
import {
  faAt,
  faPhone,
  faUserPlus,
  faWalking,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { ref } from "vue";
import { toast } from "vue-sonner";

import { toInputDate } from "@livrelibre/shared/date";
import type { Item } from "@livrelibre/shared/item";
import {
  type ContactMean as ContactMeanType,
  type OrderStatus,
  type RawOrder,
  STATUS_LABEL,
} from "@livrelibre/shared/order";

import Button from "@/components/Button.vue";
import Card from "@/components/Card.vue";
import CardBody from "@/components/CardBody.vue";
import CardFooter from "@/components/CardFooter.vue";
import CardTitle from "@/components/CardTitle.vue";
import ContactMean from "@/components/ContactMean.vue";
import FormRow from "@/components/FormRow.vue";
import Input from "@/components/Input.vue";
import OrderCustomerForm from "@/components/OrderCustomerForm.vue";
import Select from "@/components/Select.vue";
import SelectCustomer from "@/components/SelectCustomer.vue";
import SelectItem from "@/components/SelectItem.vue";
import Textarea from "@/components/Textarea.vue";
import type {
  CustomerSelection,
  OrderFormData,
  OrderFormResult,
} from "@/components/orderForm";
import type { NewItem } from "@/components/selectItem";
import { useTRPCUtils } from "@/utils/query";

const props = defineProps<{
  title: string;
  onSubmit: (order: RawOrder) => Promise<OrderFormResult>;
  data: OrderFormData;
}>();

const utils = useTRPCUtils();

const customer = ref<CustomerSelection | null>(props.data.customer ?? null);
const item = ref<Item | NewItem | null | undefined>(
  props.data.item ?? { id: null, title: props.data.itemTitle ?? "" },
);
const showCustomerForm = ref(false);

const created = ref(toInputDate(props.data.created));
const isbn = ref(props.data.item?.isbn ?? "");
const itemId = ref<number | null>(props.data.itemId ?? null);
const itemTitle = ref(props.data.itemTitle ?? props.data.item?.title ?? "");
const contact = ref<ContactMeanType>(props.data.contact ?? "unknown");
const comment = ref(props.data.comment ?? "");
const nb = ref<number | string>(props.data.nb ?? 1);
const ordered = ref<OrderStatus>(props.data.ordered ?? "new");
const paid = ref(props.data.paid ?? false);
const customerNotified = ref(props.data.customerNotified ?? false);
const customerId = ref<number | null>(
  props.data.customerId ?? props.data.customer?.id ?? null,
);

const toggleCustomerForm = () => {
  showCustomerForm.value = !showCustomerForm.value;
};

const updateCustomer = (value: CustomerSelection | null) => {
  customer.value = value;
  customerId.value = value?.id ?? null;
};

const updateItem = (value: Item | NewItem | null | undefined) => {
  item.value = value;
  itemId.value = value?.id ?? null;
  itemTitle.value = value?.title ?? "";
  isbn.value = value && "isbn" in value ? value.isbn : "";
};

const submit = async () => {
  if (isbn.value && !itemId.value) {
    if (!/^\d{10,13}$/.test(isbn.value)) {
      toast.error("ISBN invalide");
      return;
    }
    const result = await utils.fetch("isbnSearch", isbn.value);
    if (result.count === 0) {
      toast.info("Aucun article trouvé pour cet ISBN");
    }
    updateItem(result.items[0]);
    return;
  }
  if (!customerId.value) {
    toast.info("Merci de sélectionner un⋅e client⋅e");
    return;
  }
  if (!itemTitle.value) {
    toast.info("Merci de renseigner le titre ou l'ISBN de l'article");
    return;
  }
  const parsedDate = new Date(created.value);
  if (Number.isNaN(parsedDate.getTime())) {
    toast.error("Date invalide");
    return;
  }
  await props.onSubmit({
    created: parsedDate.toISOString(),
    customerId: customerId.value,
    itemId: itemId.value,
    itemTitle: itemTitle.value,
    ordered: ordered.value,
    customerNotified: customerNotified.value,
    paid: paid.value,
    comment: comment.value,
    nb: Number(nb.value),
    contact: contact.value,
  });
};
</script>

<template>
  <Card class="max-h-full flex flex-col">
    <CardTitle>{{ props.title }}</CardTitle>
    <form class="contents" @submit.prevent="submit">
      <CardBody class="flex-col gap-5">
        <div class="flex flex-col">
          <FormRow label="Client⋅e">
            <Input
              v-if="showCustomerForm"
              type="text"
              class="w-full bg-[#ccc] cursor-not-allowed"
              disabled
              value="Nouveau client"
            />
            <SelectCustomer
              v-else
              :customer="customer"
              full-width
              required
              @update:customer="updateCustomer"
            />
            <Button
              class="ml-sm self-center"
              title="Nouveau client"
              type="button"
              @click="toggleCustomerForm"
            >
              <FontAwesomeIcon :icon="faUserPlus" />
            </Button>
          </FormRow>
          <OrderCustomerForm
            v-if="showCustomerForm"
            :on-add="updateCustomer"
            :on-hide="toggleCustomerForm"
          />
          <FormRow label="Contacter par" field-class="gap-2">
            <ContactMean
              v-model="contact"
              mean="unknown"
              :is-active="contact === 'unknown'"
            >
              Non renseigné
            </ContactMean>
            <ContactMean
              v-model="contact"
              mean="in person"
              :is-active="contact === 'in person'"
            >
              <FontAwesomeIcon :icon="faWalking" class="mr-1" />
              <span>Passera</span>
            </ContactMean>
            <ContactMean
              v-model="contact"
              mean="phone"
              :is-active="contact === 'phone'"
            >
              <FontAwesomeIcon :icon="faPhone" class="mr-1" />
              <em>{{ customer?.phone }}</em>
            </ContactMean>
            <ContactMean
              v-model="contact"
              mean="mail"
              :is-active="contact === 'mail'"
            >
              <FontAwesomeIcon :icon="faAt" class="mr-1" />
              <em>{{ customer?.email }}</em>
            </ContactMean>
          </FormRow>
          <FormRow label="Date">
            <Input v-model="created" type="datetime-local" required />
          </FormRow>
          <FormRow label="ISBN">
            <Input v-model="isbn" type="text" :maxlength="13" />
          </FormRow>
          <FormRow label="Titre">
            <SelectItem :item="item" full-width @update:item="updateItem" />
          </FormRow>
          <FormRow label="Commentaires">
            <Textarea v-model="comment" />
          </FormRow>
          <FormRow label="Nb d'exemplaires">
            <Input v-model="nb" type="number" :min="1" required />
          </FormRow>
          <FormRow label="État">
            <Select v-model="ordered">
              <option
                v-for="[key, label] in Object.entries(STATUS_LABEL)"
                :key="key"
                :value="key"
              >
                {{ label }}
              </option>
            </Select>
          </FormRow>
          <FormRow
            label="Payé"
            :field-class="
              paid
                ? 'border-r-8 border-[rgba(245,0,0,0.5)] pr-2 min-h-6 w-fit'
                : ''
            "
          >
            <input v-model="paid" type="checkbox" />
          </FormRow>
          <FormRow label="Client⋅e informé⋅e">
            <input v-model="customerNotified" type="checkbox" />
          </FormRow>
        </div>
      </CardBody>
      <CardFooter>
        <div class="flex justify-end mb-sm">
          <slot />
        </div>
      </CardFooter>
    </form>
  </Card>
</template>
