// apps/web/src/components/Restricted.tsx
import type { ReactElement } from "react";

import useUser from "@/lib/useUser";

import { Alert } from "./Alert";

export const Restricted = ({
  role,
  children,
}: {
  role: string;
  children: ReactElement;
}) => {
  const { user } = useUser();
  if (user?.role !== role) {
    return (
      <div>
        <Alert type="warning">
          Vous n&rsquo;êtes pas autorisé à accéder à cette partie.
        </Alert>
      </div>
    );
  }
  return children;
};

// apps/web-vue/src/components/Restricted.vue
<script setup lang="ts">
import useUser from "@/lib/useUser";

import Alert from "./Alert.vue";

const props = defineProps<{ role: string }>();

const { user } = useUser();
</script>

<template>
  <div v-if="user?.role !== props.role">
    <Alert type="warning">
      Vous n’êtes pas autorisé à accéder à cette partie.
    </Alert>
  </div>
  <slot v-else />
</template>
