// apps/web/src/components/SelectItem.tsx
import { faCheck } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  Combobox,
  ComboboxInput,
  ComboboxOption,
  ComboboxOptions,
} from "@headlessui/react";
import { keepPreviousData } from "@tanstack/react-query";
import { clsx } from "clsx";
import { Fragment, type HTMLProps, useState } from "react";

import { formatPrice } from "@livrelibre/shared/format";
import type { Item } from "@livrelibre/shared/item";

import { COMMON_STYLES } from "@/components/FormControls";
import { trpc } from "@/utils/trpc";
import { useDebouncedValue } from "@/utils/useDebouncedValue";
import { useDelayedLoading } from "@/utils/useDelayedLoading";

export type NewItem = { id: null; title: string };

type ItemValue = Item | NewItem | null | undefined;

const getLabel = (item: ItemValue) => (item ? item.title : "");

type Props = {
  inputClass?: string;
  item: ItemValue;
  setItem: (item: ItemValue) => void;
  fullWidth?: boolean;
} & Pick<HTMLProps<HTMLInputElement>, "placeholder" | "required">;

export function SelectItem({
  inputClass,
  item,
  setItem,
  fullWidth,
  ...inputProps
}: Props) {
  const [search, setSearch] = useState("");
  const debouncedSearch = useDebouncedValue(search, 300);
  const res = trpc.quicksearch.useQuery(
    { search: debouncedSearch },
    { staleTime: 60000, placeholderData: keepPreviousData },
  );
  const showLoading = useDelayedLoading(res.isFetching, 500);

  const filteredItems = res.data?.items || [];
  const inputStyles = fullWidth
    ? COMMON_STYLES
    : COMMON_STYLES.replace("w-full", "w-fit");

  return (
    <Combobox value={item} by="id" onChange={setItem}>
      <div className={clsx("relative", fullWidth ? "w-full" : "w-fit")}>
        <ComboboxInput
          className={clsx(inputStyles, inputClass)}
          displayValue={getLabel}
          onChange={(event) => {
            setSearch(event.target.value);
          }}
          {...inputProps}
        />
        <ComboboxOptions
          className="absolute z-10 w-full max-h-56 overflow-auto rounded-md shadow-lg ring-1 ring-black/5 bg-gray-light"
          as="ul"
        >
          {showLoading && (
            <li className="px-2 py-1 text-sm italic">Chargement…</li>
          )}
          {res.isError && (
            <li className="px-2 py-1 text-sm [color:#721c24]">
              Erreur de chargement
            </li>
          )}
          {search.length > 0 && (
            <ComboboxOption value={{ id: null, title: search }}>
              {search}
            </ComboboxOption>
          )}
          {filteredItems.map((item) => (
            <ComboboxOption key={item.id} value={item} as={Fragment}>
              {({ focus, selected }) => (
                <li
                  className={clsx(
                    "px-2 flex gap-2 items-center",
                    focus ? "bg-gray-light" : "bg-white",
                  )}
                >
                  <span className={clsx(!selected && "invisible")}>
                    <FontAwesomeIcon icon={faCheck} />
                  </span>
                  <div className="flex flex-col grow py-1">
                    <span className="leading-tight">{item.title}</span>
                    <div className="text-xs">
                      <span className="mr-2">{item.distributor}</span>
                      <span className="italic mr-auto">{item.isbn}</span>
                    </div>
                  </div>
                  <span className="font-number text-sm">
                    {formatPrice(Number(item.price))}
                  </span>
                </li>
              )}
            </ComboboxOption>
          ))}
        </ComboboxOptions>
      </div>
    </Combobox>
  );
}

// apps/web-vue/src/components/SelectItem.vue
<script setup lang="ts">
import { faCheck } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import {
  Combobox,
  ComboboxInput,
  ComboboxOption,
  ComboboxOptions,
} from "@headlessui/vue";
import { keepPreviousData } from "@tanstack/vue-query";
import { clsx } from "clsx";
import { computed, ref } from "vue";

import { formatPrice } from "@livrelibre/shared/format";

import { COMMON_STYLES } from "@/components/formControls";
import type { ItemValue, NewItem } from "@/components/selectItem";
import { useTRPCQuery } from "@/utils/query";
import { useDebouncedValue } from "@/utils/useDebouncedValue";
import { useDelayedLoading } from "@/utils/useDelayedLoading";

const props = defineProps<{
  fullWidth?: boolean;
  inputClass?: string;
}>();

const item = defineModel<ItemValue>("item", { required: true });

const search = ref("");
const debouncedSearch = useDebouncedValue(search, 300);
const res = useTRPCQuery(
  "quicksearch",
  computed(() => ({ search: debouncedSearch.value })),
  { staleTime: 60000, placeholderData: keepPreviousData },
);
const showLoading = useDelayedLoading(
  computed(() => res.isFetching.value),
  500,
);
const filteredItems = computed(() => res.data.value?.items || []);
const newItemOption = computed<NewItem>(() => ({
  id: null,
  title: search.value,
}));
const inputStyles = computed(() =>
  props.fullWidth ? COMMON_STYLES : COMMON_STYLES.replace("w-full", "w-fit"),
);
</script>

<template>
  <Combobox v-model="item" by="id">
    <div :class="clsx('relative', props.fullWidth ? 'w-full' : 'w-fit')">
      <ComboboxInput
        :class="clsx(inputStyles, props.inputClass)"
        :display-value="(value: unknown) => (value as ItemValue)?.title ?? ''"
        @change="
          (event) => {
            search = (event.target as HTMLInputElement).value;
          }
        "
      />
      <ComboboxOptions
        class="absolute z-10 w-full max-h-56 overflow-auto rounded-md shadow-lg ring-1 ring-black/5 bg-gray-light"
        as="ul"
      >
        <li v-if="showLoading" class="px-2 py-1 text-sm italic">Chargement…</li>
        <li v-if="res.isError.value" class="px-2 py-1 text-sm [color:#721c24]">
          Erreur de chargement
        </li>
        <ComboboxOption v-if="search.length > 0" :value="newItemOption">
          {{ search }}
        </ComboboxOption>
        <ComboboxOption
          v-for="option in filteredItems"
          v-slot="{ active, selected }"
          :key="option.id"
          :value="option"
          as="template"
        >
          <li
            :class="
              clsx(
                'px-2 flex gap-2 items-center',
                active ? 'bg-gray-light' : 'bg-white',
              )
            "
          >
            <span :class="clsx(!selected && 'invisible')">
              <FontAwesomeIcon :icon="faCheck" />
            </span>
            <div class="flex flex-col grow py-1">
              <span class="leading-tight">{{ option.title }}</span>
              <div class="text-xs">
                <span class="mr-2">{{ option.distributor }}</span>
                <span class="italic mr-auto">{{ option.isbn }}</span>
              </div>
            </div>
            <span class="font-number text-sm">
              {{ formatPrice(Number(option.price)) }}
            </span>
          </li>
        </ComboboxOption>
      </ComboboxOptions>
    </div>
  </Combobox>
</template>
