// apps/web-vue/src/pages/best-sales.vue
<script setup lang="ts">
import { clsx } from "clsx";

import { formatNumber } from "@livrelibre/shared/format";

import Card from "@/components/Card.vue";
import CardBody from "@/components/CardBody.vue";
import CardTitle from "@/components/CardTitle.vue";
import ErrorMessage from "@/components/ErrorMessage.vue";
import Skeleton from "@/components/Skeleton.vue";
import Title from "@/components/Title.vue";
import { useTRPCQuery } from "@/utils/query";

const TH_STYLES = "sticky top-0 bg-white";

const result = useTRPCQuery("bestsales", undefined);
</script>

<template>
  <div class="[margin-left:10%] [margin-right:10%] flex flex-1 flex-col gap-lg">
    <Title>Meilleurs ventes</Title>
    <Card class="max-h-full overflow-hidden flex flex-col">
      <CardTitle>Meilleures ventes</CardTitle>
      <CardBody>
        <ErrorMessage v-if="result.isError.value" />
        <Skeleton v-else-if="result.isPending.value" :height="500">
          <template v-for="n in 17" :key="n">
            <rect
              x="2%"
              :y="(n - 1) * 30 + 10"
              width="3%"
              :height="10"
              rx="5"
            />
            <rect x="10%" :y="(n - 1) * 30 + 10" width="40%" :height="10" />
            <rect x="60%" :y="(n - 1) * 30 + 10" width="20%" :height="10" />
            <rect
              x="83%"
              :y="(n - 1) * 30 + 10"
              width="6%"
              :height="10"
              rx="5"
            />
            <rect
              x="92%"
              :y="(n - 1) * 30 + 10"
              width="6%"
              :height="10"
              rx="5"
            />
          </template>
        </Skeleton>
        <table
          v-else
          class="flex-1 [border-collapse:separate] [border-spacing:2px_0.5rem]"
        >
          <thead>
            <tr>
              <th :class="clsx(TH_STYLES, 'text-left')">#</th>
              <th :class="clsx(TH_STYLES, 'text-left')">Titre</th>
              <th :class="clsx(TH_STYLES, 'text-left')">Auteur·ice</th>
              <th :class="clsx(TH_STYLES, 'text-right')">Vendus</th>
              <th :class="clsx(TH_STYLES, 'text-right whitespace-nowrap')">
                En stock
              </th>
              <th :class="TH_STYLES"></th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="(item, i) in result.data.value ?? []" :key="item.id">
              <td>{{ i + 1 }}</td>
              <td>
                <span class="text-primary-darkest">
                  <RouterLink :to="`/item/${String(item.id)}`">
                    {{ item.title }}
                  </RouterLink>
                </span>
              </td>
              <td>{{ item.author }}</td>
              <td class="text-right font-number">
                {{ formatNumber(Number(item.count)) }}
              </td>
              <td class="pr-3 text-right font-number">
                {{ formatNumber(item.amount) }}
              </td>
              <td></td>
            </tr>
          </tbody>
        </table>
      </CardBody>
    </Card>
  </div>
</template>

// src/pages/best-sales.tsx
import Link from "next/link";
import ContentLoader from "react-content-loader";
import tw from "twin.macro";

import { Card, CardBody, CardTitle } from "@/components/Card";
import { ErrorMessage } from "@/components/ErrorMessage";
import { Title } from "@/components/Title";
import { formatNumber } from "@/utils/format";
import type { ItemWithCount } from "@/utils/item";
import { trpc } from "@/utils/trpc";

const StickyTh = tw.th`sticky top-0 bg-white`;
const ItemsTable = ({ items }: { items: ItemWithCount[] }) => (
  <table tw="flex-1 border-collapse[separate] border-spacing[2px 0.5rem]">
    <thead>
      <tr>
        <StickyTh tw="text-left">#</StickyTh>
        <StickyTh tw="text-left">Titre</StickyTh>
        <StickyTh tw="text-left">Auteur</StickyTh>
        <StickyTh tw="text-right">Vendus</StickyTh>
        <StickyTh tw="text-right whitespace-nowrap">En stock</StickyTh>
        <StickyTh></StickyTh>
      </tr>
    </thead>
    <tbody>
      {items.map((item, i) => (
        <tr key={i}>
          <td>{i + 1}</td>
          <td>
            <span tw="text-primary-darkest">
              <Link href={`/item/${item._id}`}>{item.title}</Link>
            </span>
          </td>
          <td>{item.author}</td>
          <td tw="text-right font-number">{formatNumber(item.count)}</td>
          <td tw="pr-3 text-right font-number">{formatNumber(item.amount)}</td>
          <td></td>
        </tr>
      ))}
    </tbody>
  </table>
);

const SkeletonRow = ({ n }: { n: number }) => (
  <>
    <rect x="2%" y={n * 30 + 10} width="3%" height={10} rx={5} />
    <rect x="10%" y={n * 30 + 10} width="40%" height={10} />
    <rect x="60%" y={n * 30 + 10} width="20%" height={10} />
    <rect x="83%" y={n * 30 + 10} width="6%" height={10} rx={5} />
    <rect x="92%" y={n * 30 + 10} width="6%" height={10} rx={5} />
  </>
);

const BestSalesSkeleton = () => (
  <ContentLoader height={500} width="100%">
    {Array(17)
      .fill(0)
      .map((_, i) => (
        <SkeletonRow key={i} n={i} />
      ))}
  </ContentLoader>
);

const BestSalesLoader = () => {
  const result = trpc.useQuery(["bestsales"]);
  if (result.status === "error") {
    return <ErrorMessage />;
  }
  if (result.status === "loading") {
    return <BestSalesSkeleton />;
  }
  if (result.status === "idle") {
    return null;
  }
  return <ItemsTable items={result.data} />;
};

const BestSales = (): JSX.Element => (
  <div tw="margin-left[10%] margin-right[10%] flex flex-1 flex-col gap-lg">
    <Title>Meilleurs ventes</Title>
    <Card tw="max-h-full overflow-hidden flex flex-col">
      <CardTitle>Meilleures ventes</CardTitle>
      <CardBody>
        <BestSalesLoader />
      </CardBody>
    </Card>
  </div>
);

export default BestSales;
