// apps/web-vue/src/pages/items.vue
<script setup lang="ts">
import { keepPreviousData } from "@tanstack/vue-query";
import { computed } from "vue";
import { ContentLoader } from "vue-content-loader";
import { useRoute } from "vue-router";

import { ITEMS_PER_PAGE } from "@livrelibre/shared/pagination";

import Card from "@/components/Card.vue";
import CardBody from "@/components/CardBody.vue";
import CardFooter from "@/components/CardFooter.vue";
import CardTitle from "@/components/CardTitle.vue";
import ErrorMessage from "@/components/ErrorMessage.vue";
import ItemsCard from "@/components/ItemsCard.vue";
import ItemsTable from "@/components/ItemsTable.vue";
import LoadingOverlay from "@/components/LoadingOverlay.vue";
import Pagination from "@/components/Pagination.vue";
import Title from "@/components/Title.vue";
import { useTRPCQuery } from "@/utils/query";
import { useDelayedLoading } from "@/utils/useDelayedLoading";

const route = useRoute();
const page = computed(() => {
  const queryPage = route.query.page;
  return typeof queryPage === "string" ? Number(queryPage) : 1;
});

const result = useTRPCQuery("items", page, {
  placeholderData: keepPreviousData,
});
const showLoading = useDelayedLoading(
  computed(() => result.isFetching.value),
  500,
);

const pageCount = computed(() =>
  result.data.value ? Math.ceil(result.data.value.count / ITEMS_PER_PAGE) : 0,
);
const listTitle = computed(() => {
  let title = "Tous les articles";
  if (pageCount.value > 1) {
    title += ` - Page ${String(page.value)} sur ${String(pageCount.value)}`;
  }
  return title;
});
const pageTitle = computed(() => {
  let title = "Liste des articles";
  if (pageCount.value > 1) {
    title += ` | Page ${String(page.value)} sur ${String(pageCount.value)}`;
  }
  return title;
});
</script>

<template>
  <div class="flex flex-1 flex-col gap-lg">
    <Title>Liste des articles</Title>
    <ItemsCard v-if="result.isError.value" title="Liste des articles">
      <ErrorMessage />
    </ItemsCard>
    <ItemsCard v-else-if="result.isPending.value" title="Liste des articles">
      <ContentLoader :height="300" width="100%">
        <template v-for="n in 10" :key="n">
          <rect
            x="2%"
            :y="(n - 1) * 30 + 15"
            rx="2"
            ry="2"
            width="25%"
            height="10"
          />
          <rect
            x="32%"
            :y="(n - 1) * 30 + 15"
            rx="2"
            ry="2"
            width="25%"
            height="10"
          />
          <rect
            x="62%"
            :y="(n - 1) * 30 + 15"
            rx="2"
            ry="2"
            width="25%"
            height="10"
          />
          <rect
            x="92%"
            :y="(n - 1) * 30 + 15"
            rx="2"
            ry="2"
            width="6%"
            height="10"
          />
        </template>
      </ContentLoader>
    </ItemsCard>
    <Card v-else class="max-h-full overflow-hidden flex flex-col relative">
      <Title>{{ pageTitle }}</Title>
      <CardTitle>{{ listTitle }}</CardTitle>
      <p class="mt-sm">{{ result.data.value?.count ?? 0 }} articles</p>
      <CardBody>
        <LoadingOverlay v-if="showLoading">
          <ItemsTable :items="result.data.value?.items ?? []" />
        </LoadingOverlay>
        <ItemsTable v-else :items="result.data.value?.items ?? []" />
      </CardBody>
      <CardFooter
        v-if="pageCount > 1"
        class="flex justify-center pt-6 2xl:pt-8"
      >
        <Pagination :count="pageCount" />
      </CardFooter>
    </Card>
  </div>
</template>

// src/pages/items.tsx
import { useRouter } from "next/router";
import React from "react";
import ContentLoader from "react-content-loader";

import { Card, CardBody, CardFooter, CardTitle } from "@/components/Card";
import { ErrorMessage } from "@/components/ErrorMessage";
import { ItemsCard } from "@/components/ItemsCard";
import { ItemsTable } from "@/components/ItemsTable";
import { LoadingOverlay } from "@/components/LoadingOverlay";
import { Pagination } from "@/components/Pagination";
import { Title } from "@/components/Title";
import { trpc } from "@/utils/trpc";

const SkeletonRow = ({ n }: { n: number }) => (
  <>
    <rect x="2%" y={n * 30 + 15} rx="2" ry="2" width="25%" height="10" />
    <rect x="32%" y={n * 30 + 15} rx="2" ry="2" width="25%" height="10" />
    <rect x="62%" y={n * 30 + 15} rx="2" ry="2" width="25%" height="10" />
    <rect x="92%" y={n * 30 + 15} rx="2" ry="2" width="6%" height="10" />
  </>
);

const ItemsSkeleton = (): JSX.Element => (
  <ContentLoader height={300} width="100%">
    {Array(10)
      .fill(0)
      .map((_, i) => (
        <SkeletonRow key={i} n={i} />
      ))}
  </ContentLoader>
);

const ItemsLoader = ({ page }: { page: number }) => {
  const result = trpc.items.useQuery(page, { keepPreviousData: true });
  let pageTitle = "Liste des articles";
  if (result.status === "error") {
    return (
      <ItemsCard title={pageTitle}>
        <ErrorMessage />
      </ItemsCard>
    );
  }
  if (result.status === "loading") {
    return (
      <ItemsCard title={pageTitle}>
        <ItemsSkeleton />
      </ItemsCard>
    );
  }
  const { count, pageCount, items } = result.data;
  let title = "Tous les articles";
  if (pageCount > 1) {
    const pageLabel = `Page ${page} sur ${pageCount}`;
    title += " - " + pageLabel;
    pageTitle += " | " + pageLabel;
  }
  const Wrapper = result.isFetching ? LoadingOverlay : React.Fragment;

  return (
    <Card className="max-h-full overflow-hidden flex flex-col relative">
      <Title>{pageTitle}</Title>
      <CardTitle>{title}</CardTitle>
      <p className="mt-sm">{count} articles</p>
      <CardBody>
        <Wrapper>
          <ItemsTable items={items} />
        </Wrapper>
      </CardBody>
      {pageCount > 1 ? (
        <CardFooter className="flex justify-center pt-6 2xl:pt-8">
          <Pagination count={pageCount} />
        </CardFooter>
      ) : null}
    </Card>
  );
};

const Items = (): JSX.Element => {
  const router = useRouter();
  const { page: queryPage } = router.query;
  const page = typeof queryPage === "string" ? Number(queryPage) : 1;
  return (
    <div className="flex flex-1 flex-col gap-lg">
      <Title>Liste des articles</Title>
      <ItemsLoader page={page} />
    </div>
  );
};

export default Items;
