// apps/web-vue/src/pages/login.vue
<script setup lang="ts">
import {
  faExclamationCircle,
  faEye,
  faEyeSlash,
  faSignInAlt,
  faSpinner,
  faUser,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { ref } from "vue";
import { useRouter } from "vue-router";

import Button from "@/components/Button.vue";
import Input from "@/components/Input.vue";
import Title from "@/components/Title.vue";
import { APP_NAME } from "@/lib/config";
import { useTRPCUtils } from "@/utils/query";
import type { RouterOutput } from "@/utils/trpc";

const router = useRouter();
const utils = useTRPCUtils();

const username = ref("");
const password = ref("");
const showPassword = ref(false);
const isSubmitting = ref(false);
const errorMsg = ref("");

const translateErrorMessage = (msg: string) =>
  msg === "Invalid credentials" ? "Identifiants invalides" : msg;

const onSubmit = async () => {
  isSubmitting.value = true;
  try {
    const res = await fetch("/api/login", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        username: username.value,
        password: password.value,
      }),
    });
    if (res.ok) {
      const user = (await res.json()) as RouterOutput["user"];
      utils.setData("user", undefined, user);
      await router.push("/");
    } else {
      const { error } = (await res.json()) as { error: string };
      errorMsg.value = translateErrorMessage(error);
    }
  } finally {
    isSubmitting.value = false;
  }
};
</script>

<template>
  <div class="h-full w-full relative">
    <Title>Se connecter</Title>
    <div class="bg-primary w-full h-1/2 absolute top-0" />
    <section class="flex flex-col justify-center items-center h-full relative">
      <h1 class="font-['Niconne'] [font-size:52px] text-white mb-4">
        {{ APP_NAME }}
      </h1>
      <form
        class="p-10 flex flex-col bg-white [box-shadow:0px_29px_147.5px_102.5px_hsla(0,0%,0%,0.05),0px_29px_95px_0px_hsla(0,0%,0%,0.16)]"
        @submit.prevent="onSubmit"
      >
        <h2
          class="[border-bottom:1px_solid_#ddd] pb-5 mb-5 uppercase text-center font-medium [font-size:26px]"
        >
          <FontAwesomeIcon :icon="faUser" class="mr-2" />
          Connexion
        </h2>
        <p v-if="errorMsg" class="[color:#721c24] mb-sm">
          <FontAwesomeIcon :icon="faExclamationCircle" class="mr-sm" />
          {{ errorMsg }}
        </p>
        <div class="mb-5 [color:#666] [font-size:14px]">
          <label for="username" class="uppercase font-medium"
            >Identifiant</label
          >
          <Input
            id="username"
            v-model="username"
            type="text"
            autofocus
            required
          />
        </div>
        <div class="mb-5 [color:#666] [font-size:14px]">
          <div class="flex">
            <label for="password" class="uppercase font-medium">
              Mot de passe
            </label>
            <button
              type="button"
              class="ml-auto"
              @click="showPassword = !showPassword"
            >
              <FontAwesomeIcon
                :icon="showPassword ? faEyeSlash : faEye"
                class="mr-1"
              />
              {{ showPassword ? "Masquer" : "Afficher" }}
            </button>
          </div>
          <Input
            id="password"
            v-model="password"
            :type="showPassword ? 'text' : 'password'"
            autocomplete="off"
            required
          />
        </div>
        <Button type="submit" :disabled="isSubmitting">
          <FontAwesomeIcon
            :icon="isSubmitting ? faSpinner : faSignInAlt"
            :spin="isSubmitting"
            class="mr-2"
          />
          Connexion
        </Button>
      </form>
    </section>
  </div>
</template>

// src/pages/login.tsx
import {
  faExclamationCircle,
  faEye,
  faEyeSlash,
  faSignInAlt,
  faSpinner,
  faUser,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useRouter } from "next/router";
import { useState } from "react";
import { useForm } from "react-hook-form";

import { Button } from "@/components/Button";
import { Input } from "@/components/FormControls";
import { Title } from "@/components/Title";
import { APP_NAME } from "@/lib/config";
import { trpc } from "@/utils/trpc";

const FormGroup = ({ children }: React.PropsWithChildren) => (
  <div className="mb-5 [color:#666] [font-size:14px]">{children}</div>
);

const translateErrorMessage = (msg: string) =>
  msg === "Invalid credentials" ? "Identifiants invalides" : msg;

const ErrorMsg = ({ text }: { text: string }) => (
  <p className="[color:#721c24] mb-sm">
    <FontAwesomeIcon icon={faExclamationCircle} className="mr-sm" />
    {text}
  </p>
);

type LoginFormData = {
  username: string;
  password: string;
};

const Login = () => {
  const { register, handleSubmit, formState } = useForm<LoginFormData>();
  const utils = trpc.useContext();
  const router = useRouter();
  const [errorMsg, setErrorMsg] = useState("");
  const [showPassword, setShowPassword] = useState(false);

  const onSubmit = async (data: LoginFormData) => {
    const res = await fetch("/api/login", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(data),
    });
    await utils.user.invalidate();
    if (res.ok) {
      await router.push("/");
    } else {
      const { error } = (await res.json()) as { error: string };
      setErrorMsg(translateErrorMessage(error));
    }
  };
  const { isSubmitting } = formState;

  return (
    <div className="h-full w-full relative">
      <Title>Se connecter</Title>
      <div className="bg-primary-default w-full h-1/2 absolute top-0" />
      <section className="flex flex-col justify-center items-center h-full relative">
        <h1 className="font-['Niconne'] [font-size:52px] text-white mb-4">
          {APP_NAME}
        </h1>
        <form
          onSubmit={handleSubmit(onSubmit)}
          className="[box-shadow: 0px 29px 147.5px 102.5px hsla(0, 0%, 0%, 0.05), 0px 29px 95px 0px hsla(0, 0%, 0%, 0.16) ] p-10 flex flex-col bg-white"
        >
          <h2 className="[border-bottom:1px_solid_#ddd] pb-5 mb-5 uppercase text-center font-medium [font-size:26px]">
            <FontAwesomeIcon icon={faUser} className="mr-2" />
            Connexion
          </h2>
          {errorMsg && <ErrorMsg text={errorMsg} />}
          <FormGroup>
            <label htmlFor="username" className="uppercase font-medium">
              Identifiant
            </label>
            <Input
              id="username"
              type="text"
              {...register("username")}
              autoFocus
              required
            />
          </FormGroup>
          <FormGroup>
            <div className="flex">
              <label htmlFor="password" className="uppercase font-medium">
                Mot de passe
              </label>
              <button
                type="button"
                className="ml-auto"
                onClick={() => setShowPassword((show) => !show)}
              >
                <FontAwesomeIcon
                  icon={showPassword ? faEyeSlash : faEye}
                  className="mr-1"
                />
                {showPassword ? "Masquer" : "Afficher"}
              </button>
            </div>
            <Input
              id="password"
              type={showPassword ? "text" : "password"}
              autoComplete="off"
              {...register("password")}
              required
            />
          </FormGroup>
          <Button type="submit" disabled={isSubmitting}>
            <FontAwesomeIcon
              icon={isSubmitting ? faSpinner : faSignInAlt}
              spin={isSubmitting}
              className="mr-2"
            />
            Connexion
          </Button>
        </form>
      </section>
    </div>
  );
};

Login.isPublic = true;

export default Login;
