// apps/web-vue/src/components/AddToCartButton.vue
<script setup lang="ts">
import {
  faCartPlus,
  faShoppingCart,
  faSpinner,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { clsx } from "clsx";
import { computed } from "vue";

import type { Bookmark } from "@livrelibre/server/server/bookmarks";

import { useAddToCart } from "@/utils/useAddToCart";

const props = defineProps<{ item: Bookmark; className?: string }>();

const { mutate, isPending } = useAddToCart();

const icon = computed(() => {
  if (isPending.value) return faSpinner;
  return props.item.amount > 0 ? faCartPlus : faShoppingCart;
});
</script>

<template>
  <button
    :class="
      clsx(
        'p-xs mr-xs disabled:(cursor-not-allowed opacity-80) hover:text-primary-darkest',
        props.className,
      )
    "
    title="Ajouter au panier"
    type="button"
    :disabled="props.item.amount === 0"
    @click="mutate({ id: props.item.id })"
  >
    <FontAwesomeIcon :icon="icon" :spin="isPending" />
  </button>
</template>

// src/components/AddToCartButton.tsx
import {
  faCartPlus,
  faShoppingCart,
  faSpinner,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { clsx } from "clsx";

import type { Bookmark } from "@livrelibre/server/server/bookmarks";
import { useAddToCart } from "@/utils/useAddToCart";

export const AddToCartButton = ({
  item,
  className,
}: {
  item: Bookmark;
  className?: string;
}) => {
  let icon = item.amount > 0 ? faCartPlus : faShoppingCart;
  const { mutate, isPending } = useAddToCart();
  if (isPending) {
    icon = faSpinner;
  }
  return (
    <button
      className={clsx(
        "p-xs mr-xs disabled:(cursor-not-allowed opacity-80) hover:text-primary-darkest",
        className,
      )}
      name="Ajouter au panier"
      title="Ajouter au panier"
      type="button"
      onClick={() => {
        mutate({ id: item.id });
      }}
      disabled={item.amount === 0}
    >
      <FontAwesomeIcon icon={icon} spin={isPending} />
    </button>
  );
};
