// apps/web/src/pages/orders.tsx
import { faPlus } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import clsx from "clsx";
import React, { type ReactElement } from "react";

import {
  type CustomerOrders,
  ORDER_STATUS,
  type OrderRow,
  type OrderStatus,
  STATUS_LABEL,
  deserializeOrder,
  zOrderStatus,
  zOrderStatusArray,
} from "@livrelibre/shared/order";
import { norm } from "@livrelibre/shared/utils";

import { LinkButton } from "@/components/Button";
import { Card, CardBody, CardTitle } from "@/components/Card";
import { ErrorMessage } from "@/components/ErrorMessage";
import { Input } from "@/components/FormControls";
import { ItemsCard } from "@/components/ItemsCard";
import { OrdersTable, OrdersTableByCustomer } from "@/components/OrdersTable";
import { StatusCircle } from "@/components/StatusCircle";
import { Title } from "@/components/Title";
import { trpc } from "@/utils/trpc";
import { useDebouncedValue } from "@/utils/useDebouncedValue";
import { useQueryParams } from "@/utils/useQueryParams";

const getStatus = (query: string | string[] | undefined): OrderStatus[] => {
  const statusList = zOrderStatusArray.safeParse(query);
  if (statusList.success) {
    return statusList.data;
  }
  const status = zOrderStatus.safeParse(query);
  if (status.success) {
    return [status.data];
  }
  return ["new", "received", "unavailable", "other", "canceled"];
};

const Tile = ({
  status,
  checked,
  onChange,
}: {
  status: OrderStatus;
  checked: boolean;
  onChange?: React.ChangeEventHandler<HTMLInputElement>;
}) => {
  const id = `chk-${status}`;
  return (
    <div>
      <input
        type="checkbox"
        name={status}
        id={id}
        checked={checked}
        className="peer absolute w-0 h-0 overflow-hidden outline-none"
        onChange={onChange}
      />
      <label
        htmlFor={id}
        className={clsx(
          "flex flex-col items-center justify-center gap-2 shrink-0",
          "p-1 border-2 w-20 h-16 rounded cursor-pointer",
          "peer-focus-visible:ring-3 peer-focus-visible:ring-primary/50",
          "hover:ring-2 hover:ring-primary/50 ",
          checked
            ? "border-primary text-primary-darkest"
            : "border-[#ccc] saturate-0 opacity-75",
        )}
      >
        <StatusCircle status={status} className="scale-125" />
        <span className="text-xs font-medium">{STATUS_LABEL[status]}</span>
      </label>
    </div>
  );
};

const OrdersLoader = () => {
  const { query, push } = useQueryParams();
  const orderStatus = getStatus(query.status);
  const result = trpc.orders.useQuery(orderStatus);
  const setOrderStatus = (status: OrderStatus[]) => {
    void push({ query: { ...query, status } });
  };

  const pageTitle = "Liste des commandes";
  if (result.status === "error") {
    return (
      <ItemsCard title={pageTitle}>
        <ErrorMessage />
      </ItemsCard>
    );
  }

  const orderRows: OrderRow[] =
    result.status === "pending" ? [] : result.data.map(deserializeOrder);

  const cardTitle =
    result.status === "pending"
      ? "Chargement"
      : `${orderRows.length} commande${orderRows.length > 1 ? "s" : ""}`;

  const updateStatus = (status: OrderStatus) => () => {
    const newStatus = orderStatus.includes(status)
      ? orderStatus.filter((s) => s !== status)
      : orderStatus.concat(status);
    setOrderStatus(newStatus);
  };

  return (
    <Card className="max-h-full overflow-hidden flex flex-col relative">
      <Title>{pageTitle}</Title>
      <CardTitle className="flex items-center">
        {cardTitle}
        <LinkButton to="/order/new" className="ml-auto">
          <FontAwesomeIcon icon={faPlus} className="mr-2" />
          Nouvelle commande
        </LinkButton>
      </CardTitle>
      <CardBody className="flex-col">
        <OrdersBody orders={orderRows}>
          {ORDER_STATUS.map((status) => (
            <Tile
              key={status}
              status={status}
              checked={orderStatus.includes(status)}
              onChange={updateStatus(status)}
            />
          ))}
        </OrdersBody>
      </CardBody>
    </Card>
  );
};

type Order = CustomerOrders["orders"][number];
const compareOrders = (reverse: boolean) => (a: Order, b: Order) => {
  const direction = reverse ? -1 : 1;
  return direction * (b.created.getTime() - a.created.getTime() || b.id - a.id);
};

const groupOrdersByCustomer = (
  orders: OrderRow[],
  reverse: boolean,
): CustomerOrders[] => {
  const groups: Map<
    number,
    {
      customer: CustomerOrders["customer"];
      orders: Order[];
      maxDate: Date;
    }
  > = new Map();
  for (const order of orders) {
    const group = groups.get(order.customerId);
    if (!group) {
      groups.set(order.customerId, {
        customer: {
          email: order.email,
          phone: order.phone,
          name: order.customerName,
        },
        orders: [order],
        maxDate: order.created,
      });
      continue;
    }
    if (order.created > group.maxDate) {
      group.maxDate = order.created;
    }
    group.orders.push(order);
  }
  return [...groups.values()].map((group) => {
    group.orders.sort(compareOrders(reverse));
    return group;
  });
};

const filterGroups = (orders: CustomerOrders[], search: string) =>
  search === ""
    ? orders
    : orders.filter(
        (order) =>
          norm(order.customer.name).toLowerCase().includes(norm(search)) ||
          order.orders.some(
            (o) =>
              o.isbn?.includes(search) ||
              norm(o.itemTitle.toLowerCase()).includes(norm(search)),
          ),
      );

const filterOrders = (orders: OrderRow[], search: string) =>
  search === ""
    ? orders
    : orders.filter(
        (order) =>
          norm(order.customerName).toLowerCase().includes(norm(search)) ||
          order.isbn?.includes(search) ||
          norm(order.itemTitle.toLowerCase()).includes(norm(search)),
      );

const OrdersBody = ({
  orders,
  children,
}: React.PropsWithChildren<{ orders: OrderRow[] }>) => {
  const { query, push } = useQueryParams();
  const search = typeof query.search === "string" ? query.search : "";
  const [searchInput, setSearchInput] = React.useState(search);
  const debouncedSearch = useDebouncedValue(searchInput, 300);

  const pushRef = React.useRef({ query, push, search });
  pushRef.current = { query, push, search };
  const inputRef = React.useRef(searchInput);
  inputRef.current = searchInput;

  React.useEffect(() => {
    const { query, push, search } = pushRef.current;
    const normalized = debouncedSearch.toLowerCase();
    if (normalized === search) return;
    void push({ query: { ...query, search: normalized }, replace: true });
  }, [debouncedSearch]);

  React.useEffect(() => {
    if (search !== inputRef.current.toLowerCase()) {
      setSearchInput(search);
    }
  }, [search]);

  const groupByCustomer = query.group !== "0";
  const toggleGroup = () => {
    const group = 1 - Number(groupByCustomer);
    void push({ query: { ...query, group } });
  };
  const invertInnerSort = query.sortBy === "date";

  return (
    <>
      <div className="flex gap-2 items-center flex-wrap">
        <div className="flex flex-col mb-2 mr-auto">
          <Input
            value={searchInput}
            onChange={(e) => {
              setSearchInput(e.target.value);
            }}
            className="text-base mb-1 !w-[30rem]"
            placeholder="Nom, prénom, titre, ISBN"
          />
          <div>
            <label htmlFor="groupByCustomer" className="mr-2 cursor-pointer">
              Grouper les commandes par client⋅e
            </label>
            <input
              id="groupByCustomer"
              type="checkbox"
              checked={groupByCustomer}
              onChange={toggleGroup}
            />
          </div>
        </div>
        <div className="flex gap-2 mr-1">{children}</div>
      </div>
      <div className="overflow-auto flex mt-2">
        {groupByCustomer ? (
          <OrdersTableByCustomer
            items={filterGroups(
              groupOrdersByCustomer(orders, invertInnerSort),
              search,
            )}
          />
        ) : (
          <OrdersTable items={filterOrders(orders, search)} />
        )}
      </div>
    </>
  );
};

const Orders = (): ReactElement => {
  return (
    <div className="flex flex-1 flex-col gap-lg">
      <Title>Liste des commandes</Title>
      <OrdersLoader />
    </div>
  );
};

export default Orders;

// apps/web-vue/src/pages/orders.vue
<script setup lang="ts">
import { faPlus } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { computed, ref, watch } from "vue";

import {
  ORDER_STATUS,
  type OrderRow,
  type OrderStatus,
  zOrderStatus,
  zOrderStatusArray,
} from "@livrelibre/shared/order";

import Card from "@/components/Card.vue";
import CardBody from "@/components/CardBody.vue";
import CardTitle from "@/components/CardTitle.vue";
import ErrorMessage from "@/components/ErrorMessage.vue";
import Input from "@/components/Input.vue";
import ItemsCard from "@/components/ItemsCard.vue";
import LinkButton from "@/components/LinkButton.vue";
import OrdersTable from "@/components/OrdersTable.vue";
import OrdersTableByCustomer from "@/components/OrdersTableByCustomer.vue";
import Title from "@/components/Title.vue";
import StatusTile from "@/components/orders/StatusTile.vue";
import {
  filterGroups,
  filterOrders,
  groupOrdersByCustomer,
} from "@/components/orders/group";
import { useTRPCQuery } from "@/utils/query";
import { useDebouncedValue } from "@/utils/useDebouncedValue";
import { useQueryParams } from "@/utils/useQueryParams";

const getStatus = (query: string | string[] | undefined): OrderStatus[] => {
  const statusList = zOrderStatusArray.safeParse(query);
  if (statusList.success) {
    return statusList.data;
  }
  const status = zOrderStatus.safeParse(query);
  if (status.success) {
    return [status.data];
  }
  return ["new", "received", "unavailable", "other", "canceled"];
};

const { query, push } = useQueryParams();

const orderStatus = computed(() => getStatus(query.value.status));
const result = useTRPCQuery("orders", orderStatus);
const orderRows = computed<OrderRow[]>(() =>
  (result.data.value ?? []).map((order) => ({
    ...order,
    created: new Date(order.created),
  })),
);

const setOrderStatus = (status: OrderStatus[]) => {
  void push({ query: { ...query.value, status } });
};
const updateStatus = (status: OrderStatus) => () => {
  const newStatus = orderStatus.value.includes(status)
    ? orderStatus.value.filter((s) => s !== status)
    : orderStatus.value.concat(status);
  setOrderStatus(newStatus);
};

const search = computed(() =>
  typeof query.value.search === "string" ? query.value.search : "",
);
const searchInput = ref(search.value);
const debouncedSearch = useDebouncedValue(searchInput, 300);

watch(debouncedSearch, (value) => {
  const normalized = value.toLowerCase();
  if (normalized === search.value) return;
  void push({ query: { ...query.value, search: normalized }, replace: true });
});
watch(search, (value) => {
  if (value !== searchInput.value.toLowerCase()) {
    searchInput.value = value;
  }
});

const groupByCustomer = computed(() => query.value.group !== "0");
const toggleGroup = () => {
  const group = 1 - Number(groupByCustomer.value);
  void push({ query: { ...query.value, group } });
};
const invertInnerSort = computed(() => query.value.sortBy === "date");

const cardTitle = computed(() =>
  result.isPending.value
    ? "Chargement"
    : `${String(orderRows.value.length)} commande${orderRows.value.length > 1 ? "s" : ""}`,
);

const groupedOrders = computed(() =>
  filterGroups(
    groupOrdersByCustomer(orderRows.value, invertInnerSort.value),
    search.value,
  ),
);
const filteredOrders = computed(() =>
  filterOrders(orderRows.value, search.value),
);
</script>

<template>
  <div class="flex flex-1 flex-col gap-lg">
    <Title>Liste des commandes</Title>
    <ItemsCard v-if="result.isError.value" title="Liste des commandes">
      <ErrorMessage />
    </ItemsCard>
    <Card v-else class="max-h-full overflow-hidden flex flex-col relative">
      <Title>Liste des commandes</Title>
      <CardTitle class="flex items-center">
        {{ cardTitle }}
        <LinkButton to="/order/new" class="ml-auto">
          <FontAwesomeIcon :icon="faPlus" class="mr-2" />
          Nouvelle commande
        </LinkButton>
      </CardTitle>
      <CardBody class="flex-col">
        <div class="flex gap-2 items-center flex-wrap">
          <div class="flex flex-col mb-2 mr-auto">
            <Input
              v-model="searchInput"
              class="text-base mb-1 !w-[30rem]"
              placeholder="Nom, prénom, titre, ISBN"
            />
            <div>
              <label for="groupByCustomer" class="mr-2 cursor-pointer">
                Grouper les commandes par client⋅e
              </label>
              <input
                id="groupByCustomer"
                type="checkbox"
                :checked="groupByCustomer"
                @change="toggleGroup"
              />
            </div>
          </div>
          <div class="flex gap-2 mr-1">
            <StatusTile
              v-for="status in ORDER_STATUS"
              :key="status"
              :status="status"
              :checked="orderStatus.includes(status)"
              @toggle="updateStatus(status)()"
            />
          </div>
        </div>
        <div class="overflow-auto flex mt-2">
          <OrdersTableByCustomer
            v-if="groupByCustomer"
            :items="groupedOrders"
          />
          <OrdersTable v-else :items="filteredOrders" />
        </div>
      </CardBody>
    </Card>
  </div>
</template>
