// apps/web-vue/src/components/Layout/QuickSearch.vue
<script setup lang="ts">
import { faSearch, faSpinner } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { ref } from "vue";
import { useRouter } from "vue-router";
import { toast } from "vue-sonner";

import { useTRPCUtils } from "@/utils/query";

const router = useRouter();
const utils = useTRPCUtils();
const isLoading = ref(false);
const search = ref("");

const submit = async () => {
  const value = search.value;
  if (value.length === 0) {
    return;
  }
  if (/^\d{10,}$/.test(value)) {
    isLoading.value = true;
    try {
      const result = await utils.fetch("isbnSearch", value);
      if (result.count === 0) {
        toast.info("Aucun article trouvé pour cet ISBN");
        return;
      }
      await router.push(`/item/${String(result.items[0].id)}`);
    } finally {
      isLoading.value = false;
    }
    return;
  }
  await router.push(`/quicksearch?search=${encodeURIComponent(value)}`);
};
</script>

<template>
  <form
    role="search"
    class="flex p-sm [width:27rem] relative"
    @submit.prevent="submit"
  >
    <input
      v-model="search"
      type="text"
      class="flex-1 [padding:5px_10px] rounded bg-white/80 pr-7 focus-visible:ring-2 focus-visible:ring-inset focus-visible:outline-none [--tw-ring-color:#AAA]"
      placeholder="ISBN, titre, auteur·ice"
      name="search"
    />
    <button
      type="submit"
      class="text-black absolute top-2 bottom-2 right-1 px-2"
      aria-label="Rechercher"
      :disabled="isLoading"
    >
      <FontAwesomeIcon
        :icon="isLoading ? faSpinner : faSearch"
        :spin="isLoading"
        class="mx-1"
      />
    </button>
  </form>
</template>

// src/components/Dashboard/QuickSearch.tsx
import { Card } from "@/components/Card";
import { ButtonWithInput } from "@/components/Button";
import { InputWithButton } from "@/components/FormControls";
import { faSearch } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import "twin.macro";
import type { DOMAttributes } from "react";
import { useRouter } from "next/router";

export const QuickSearch = (): JSX.Element => {
  const router = useRouter();

  const handleSubmit: DOMAttributes<HTMLFormElement>["onSubmit"] = (event) => {
    event.preventDefault();
    const search: string = event.currentTarget.search.value;
    router.push({ pathname: "/quicksearch", query: { search } });
  };

  return (
    <Card title="Articles - Recherche rapide" tw="min-width[24rem]">
      <form tw="flex p-sm flex-1" onSubmit={handleSubmit}>
        <InputWithButton
          type="text"
          placeholder="ISBN, titre, auteur"
          name="search"
          tw="flex-1"
        />
        <ButtonWithInput>
          <FontAwesomeIcon icon={faSearch} tw="mr-sm" />
          Rechercher
        </ButtonWithInput>
      </form>
    </Card>
  );
};
