// src/pages/sale/[year]/[month].tsx
import { clsx } from "clsx";
import Link from "next/link";
import { useRouter } from "next/router";
import type { ReactElement } from "react";
import ContentLoader from "react-content-loader";

import { Card, CardBody, CardTitle } from "@/components/Card";
import { ErrorMessage } from "@/components/ErrorMessage";
import { CategoriesTable } from "@/components/PaymentStats/CategoriesTable";
import { CategorySkeleton } from "@/components/PaymentStats/CategorySkeleton";
import { Restricted } from "@/components/Restricted";
import { StatsByTVA } from "@/components/TVAStats/StatsByTVA";
import { TVASkeleton } from "@/components/TVAStats/TVASkeleton";
import { Title } from "@/components/Title";
import { formatPrice } from "@livrelibre/shared/format";
import { ITEM_TYPES } from "@livrelibre/shared/item";
import { type RouterOutput, trpc } from "@/utils/trpc";

const TH_STYLES = "sticky top-0 bg-white";

type TSalesByDay = RouterOutput["salesByMonth"]["salesByDay"];

const formatDate = (date: string) => date.split("-").reverse().join("/");
const makeSaleURL = (date: string) => `/sale/${date.split("-").join("/")}`;

const SalesTable = ({ sales }: { sales: TSalesByDay }) => {
  const router = useRouter();
  return (
    <table className="flex-1">
      <thead>
        <tr>
          <th className={clsx(TH_STYLES, "text-left pl-2")}>Jour</th>
          <th className={clsx(TH_STYLES, "text-right")}>Nombre de ventes</th>
          <th className={clsx(TH_STYLES, "text-right")}>Recette totale</th>
        </tr>
      </thead>
      <tbody className="[line-height:2.3rem]">
        {sales.map((sale, i) => (
          <tr
            key={i}
            className="cursor-pointer hover:bg-gray-light"
            onClick={() => router.push({ pathname: makeSaleURL(sale.date) })}
          >
            <td className="pl-2">
              <Link href={makeSaleURL(sale.date)}>{formatDate(sale.date)}</Link>
            </td>
            <td className="text-right font-number">{sale.count}</td>
            <td className="text-right font-number pr-2">
              {formatPrice(Number(sale.total))}
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  );
};

const SalesSkeletonRow = ({ n }: { n: number }) => (
  <>
    <rect x="5%" y={n * 30 + 15} rx="2" ry="2" width="19%" height="10" />
    <rect x="27%" y={n * 30 + 15} rx="2" ry="2" width="19%" height="10" />
    <rect x="49%" y={n * 30 + 15} rx="2" ry="2" width="19%" height="10" />
    <rect x="71%" y={n * 30 + 13} rx="2" ry="2" width="19%" height="14" />
  </>
);

const SalesSkeleton = (): ReactElement => (
  <ContentLoader height={600} width="100%">
    {Array(20)
      .fill(0)
      .map((_, i) => (
        <SalesSkeletonRow key={i} n={i} />
      ))}
  </ContentLoader>
);

type MonthProps = {
  month: string;
  year: string;
};

const SalesLoader = (props: MonthProps) => {
  const result = trpc.salesByMonth.useQuery(props);
  if (result.isError) {
    return <ErrorMessage />;
  }
  if (result.isPending) {
    return <SalesSkeleton />;
  }
  return <SalesTable sales={result.data.salesByDay} />;
};

const SalesCard = () => {
  const router = useRouter();
  const { year, month } = router.query;
  if (typeof month !== "string" || typeof year !== "string") {
    return null;
  }
  const monthLabel = new Date(
    Number(year),
    Number(month) - 1,
  ).toLocaleDateString("fr", { month: "long", year: "numeric" });
  const title = `Liste des ventes - ${monthLabel}`;
  return (
    <Card className="flex flex-col flex-1 max-h-full overflow-hidden">
      <CardTitle>{title}</CardTitle>
      <CardBody>
        <SalesLoader month={month} year={year} />
      </CardBody>
    </Card>
  );
};

const TVALoader = (props: MonthProps) => {
  const result = trpc.salesByMonth.useQuery(props);
  if (result.isError) {
    return <ErrorMessage />;
  }
  if (result.isPending) {
    return <TVASkeleton />;
  }
  return <StatsByTVA stats={result.data.stats} />;
};

const TVACard = () => {
  const router = useRouter();
  const { year, month } = router.query;
  if (typeof month !== "string" || typeof year !== "string") {
    return null;
  }
  return (
    <Card className="[min-height:12rem] flex flex-col">
      <CardTitle>Répartition par TVA</CardTitle>
      <CardBody>
        <TVALoader month={month} year={year} />
      </CardBody>
    </Card>
  );
};

const CategoriesLoader = (props: MonthProps) => {
  const result = trpc.salesByMonth.useQuery(props);
  if (result.isError) {
    return <ErrorMessage />;
  }
  if (result.isPending) {
    return <CategorySkeleton />;
  }
  const categories = result.data.itemTypes.map((it) => ({
    ...it,
    label: ITEM_TYPES[it.itemType],
  }));
  return <CategoriesTable categories={categories} />;
};

const CategoriesCard = () => {
  const router = useRouter();
  const { year, month } = router.query;
  if (typeof month !== "string" || typeof year !== "string") {
    return null;
  }
  return (
    <Card>
      <CardTitle>Répartition par catégorie</CardTitle>
      <CardBody>
        <CategoriesLoader month={month} year={year} />
      </CardBody>
    </Card>
  );
};

const SalesByMonth = (): ReactElement => {
  return (
    <Restricted role="admin">
      <div className="flex items-start gap-lg flex-1 flex-wrap">
        <Title>Voir un article</Title>
        <SalesCard />
        <div className="flex flex-col gap-lg flex-1 max-h-full">
          <TVACard />
          <CategoriesCard />
        </div>
      </div>
    </Restricted>
  );
};

export default SalesByMonth;

// apps/web-vue/src/pages/sale/[year]/[month].vue
<script setup lang="ts">
import { clsx } from "clsx";
import { computed } from "vue";
import { RouterLink, useRoute, useRouter } from "vue-router";

import { formatPrice } from "@livrelibre/shared/format";
import { ITEM_TYPES } from "@livrelibre/shared/item";

import Card from "@/components/Card.vue";
import CardBody from "@/components/CardBody.vue";
import CardTitle from "@/components/CardTitle.vue";
import ErrorMessage from "@/components/ErrorMessage.vue";
import CategoriesTable from "@/components/PaymentStats/CategoriesTable.vue";
import CategorySkeleton from "@/components/PaymentStats/CategorySkeleton.vue";
import Restricted from "@/components/Restricted.vue";
import Skeleton from "@/components/Skeleton.vue";
import StatsByTVA from "@/components/TVAStats/StatsByTVA.vue";
import TVASkeleton from "@/components/TVAStats/TVASkeleton.vue";
import Title from "@/components/Title.vue";
import { useTRPCQuery } from "@/utils/query";

const TH_STYLES = "sticky top-0 bg-white";

const route = useRoute();
const router = useRouter();

const year = computed(() => String(route.params.year));
const month = computed(() => String(route.params.month));
const params = computed(() => ({ month: month.value, year: year.value }));

const result = useTRPCQuery("salesByMonth", params);

const formatDate = (date: string) => date.split("-").reverse().join("/");
const makeSaleURL = (date: string) => `/sale/${date.split("-").join("/")}`;
const goToSale = (date: string) => {
  void router.push(makeSaleURL(date));
};

const monthLabel = computed(() =>
  new Date(Number(year.value), Number(month.value) - 1).toLocaleDateString(
    "fr",
    { month: "long", year: "numeric" },
  ),
);
const categories = computed(() =>
  (result.data.value?.itemTypes ?? []).map((item) => ({
    ...item,
    label: ITEM_TYPES[item.itemType],
  })),
);
</script>

<template>
  <Restricted role="admin">
    <div class="flex items-start gap-lg flex-1 flex-wrap">
      <Title>Ventes du mois</Title>
      <Card class="flex flex-col flex-1 max-h-full overflow-hidden">
        <CardTitle>Liste des ventes - {{ monthLabel }}</CardTitle>
        <CardBody>
          <ErrorMessage v-if="result.isError.value" />
          <Skeleton v-else-if="result.isPending.value" :height="600">
            <template v-for="n in 20" :key="n">
              <rect
                x="5%"
                :y="(n - 1) * 30 + 15"
                rx="2"
                ry="2"
                width="19%"
                height="10"
              />
              <rect
                x="27%"
                :y="(n - 1) * 30 + 15"
                rx="2"
                ry="2"
                width="19%"
                height="10"
              />
              <rect
                x="49%"
                :y="(n - 1) * 30 + 15"
                rx="2"
                ry="2"
                width="19%"
                height="10"
              />
              <rect
                x="71%"
                :y="(n - 1) * 30 + 13"
                rx="2"
                ry="2"
                width="19%"
                height="14"
              />
            </template>
          </Skeleton>
          <table v-else class="flex-1">
            <thead>
              <tr>
                <th :class="clsx(TH_STYLES, 'text-left pl-2')">Jour</th>
                <th :class="clsx(TH_STYLES, 'text-right')">Nombre de ventes</th>
                <th :class="clsx(TH_STYLES, 'text-right')">Recette totale</th>
              </tr>
            </thead>
            <tbody class="[line-height:2.3rem]">
              <tr
                v-for="(sale, i) in result.data.value?.salesByDay ?? []"
                :key="i"
                class="cursor-pointer hover:bg-gray-light"
                @click="goToSale(sale.date)"
              >
                <td class="pl-2">
                  <RouterLink :to="makeSaleURL(sale.date)">
                    {{ formatDate(sale.date) }}
                  </RouterLink>
                </td>
                <td class="text-right font-number">{{ sale.count }}</td>
                <td class="text-right font-number pr-2">
                  {{ formatPrice(Number(sale.total)) }}
                </td>
              </tr>
            </tbody>
          </table>
        </CardBody>
      </Card>
      <div class="flex flex-col gap-lg flex-1 max-h-full">
        <Card class="[min-height:12rem] flex flex-col">
          <CardTitle>Répartition par TVA</CardTitle>
          <CardBody>
            <ErrorMessage v-if="result.isError.value" />
            <TVASkeleton v-else-if="result.isPending.value" />
            <StatsByTVA v-else :stats="result.data.value?.stats ?? []" />
          </CardBody>
        </Card>
        <Card>
          <CardTitle>Répartition par catégorie</CardTitle>
          <CardBody>
            <ErrorMessage v-if="result.isError.value" />
            <CategorySkeleton v-else-if="result.isPending.value" />
            <CategoriesTable v-else :categories="categories" />
          </CardBody>
        </Card>
      </div>
    </div>
  </Restricted>
</template>
