// apps/web-vue/src/pages/advancedSearch.vue
<script setup lang="ts">
import { keepPreviousData } from "@tanstack/vue-query";
import { computed } from "vue";
import { RouterLink } from "vue-router";

import { formatTVA } from "@livrelibre/shared/format";
import { ITEM_TYPES } from "@livrelibre/shared/item";
import { ITEMS_PER_PAGE } from "@livrelibre/shared/pagination";
import { isIn } from "@livrelibre/shared/utils";

import Card from "@/components/Card.vue";
import CardBody from "@/components/CardBody.vue";
import CardFooter from "@/components/CardFooter.vue";
import CardTitle from "@/components/CardTitle.vue";
import ErrorMessage from "@/components/ErrorMessage.vue";
import ItemsTable from "@/components/ItemsTable.vue";
import LoadingOverlay from "@/components/LoadingOverlay.vue";
import Pagination from "@/components/Pagination.vue";
import Title from "@/components/Title.vue";
import { useTRPCQuery } from "@/utils/query";
import { useDelayedLoading } from "@/utils/useDelayedLoading";
import { useQueryParams } from "@/utils/useQueryParams";

const CARD_STYLES = "max-h-full overflow-hidden flex flex-col relative";

const FIELD_LABELS: Record<string, string> = {
  type: "Type",
  isbn: "ISBN",
  author: "Auteur·ice",
  title: "Titre",
  publisher: "Maison d'édition",
  distributor: "Distributeur",
  keywords: "Mots-clés",
  datebought: "Date d'achat",
  comments: "Commentaires",
  price: "Prix de vente",
  amount: "Quantité",
  tva: "TVA",
};

const formatRow = ([key, value]: [string, string]) => {
  const fieldName = isIn(FIELD_LABELS, key) ? FIELD_LABELS[key] : key;
  let fieldValue = value;
  if (key === "type" && isIn(ITEM_TYPES, value)) {
    fieldValue = ITEM_TYPES[value];
  } else if (key === "tva") {
    fieldValue = formatTVA(value) || "";
  }
  return `${fieldName}: ${fieldValue}`;
};

const getQueryLabel = (query: Record<string, string>) =>
  Object.entries(query)
    .filter(([, value]) => value !== "")
    .map(formatRow)
    .join(", ");

const { query, push } = useQueryParams();

const toggleStock = async () => {
  const { inStock: _inStock, ...rest } = query.value;
  if (!query.value.inStock) {
    rest.inStock = "1";
  }
  await push({ query: rest });
};

const searchQuery = computed(() => {
  const body: Record<string, string> = {};
  for (const [key, value] of Object.entries(query.value)) {
    if (typeof value === "string" && key !== "page") {
      body[key] = value;
    }
  }
  return body;
});
const page = computed(() => {
  const queryPage = query.value.page;
  return typeof queryPage === "string" ? Number(queryPage) : 1;
});

const result = useTRPCQuery(
  "advancedSearch",
  computed(() => ({ search: searchQuery.value, page: page.value })),
  { placeholderData: keepPreviousData },
);
const showLoading = useDelayedLoading(
  computed(() => result.isFetching.value),
  500,
);

const pageCount = computed(() =>
  result.data.value ? Math.ceil(result.data.value.count / ITEMS_PER_PAGE) : 0,
);
const queryLabel = computed(() => getQueryLabel(searchQuery.value));
const cardTitle = computed(() => {
  let title = "Recherche avancée";
  if (pageCount.value > 1) {
    title += ` - Page ${String(page.value)} sur ${String(pageCount.value)}`;
  }
  return title;
});
</script>

<template>
  <div class="flex flex-1 flex-col gap-lg">
    <Title>Recherche avancée</Title>
    <Card
      v-if="result.isSuccess.value && result.data.value?.count === 0"
      :class="CARD_STYLES"
    >
      <CardTitle>{{ cardTitle }}</CardTitle>
      <label class="self-end cursor-pointer mr-6 ml-auto">
        <span>En stock</span>
        <input
          type="checkbox"
          class="ml-2"
          :checked="query.inStock === '1'"
          @change="toggleStock"
        />
      </label>
      <CardBody>Aucun résultat pour "{{ queryLabel }}"</CardBody>
      <p class="mt-2">
        <RouterLink to="/search" class="text-primary-darkest">
          Nouvelle recherche
        </RouterLink>
      </p>
    </Card>
    <Card v-else :class="CARD_STYLES">
      <CardTitle>{{ cardTitle }}</CardTitle>
      <div class="flex flex-1">
        <p>
          Recherche en cours…<template v-if="result.isSuccess.value">
            : {{ result.data.value?.count }} résultat{{
              (result.data.value?.count ?? 0) > 1 ? "s" : ""
            }}
            pour {{ queryLabel }}</template
          >
        </p>
        <label class="self-end cursor-pointer mr-6 ml-auto">
          <span>En stock</span>
          <input
            type="checkbox"
            class="ml-2"
            :checked="query.inStock === '1'"
            @change="toggleStock"
          />
        </label>
      </div>
      <CardBody>
        <ErrorMessage v-if="result.isError.value" />
        <LoadingOverlay v-if="result.isSuccess.value && showLoading">
          <ItemsTable :items="result.data.value?.items ?? []" />
        </LoadingOverlay>
        <ItemsTable
          v-else-if="result.isSuccess.value"
          :items="result.data.value?.items ?? []"
        />
      </CardBody>
      <CardFooter
        v-if="pageCount > 1"
        class="flex justify-center pt-6 2xl:pt-8"
      >
        <Pagination :count="pageCount" />
      </CardFooter>
    </Card>
  </div>
</template>

// apps/web/src/pages/advancedSearch.tsx
import * as React from "react";
import { keepPreviousData } from "@tanstack/react-query";
import { Link } from "react-router";

import { formatTVA } from "@livrelibre/shared/format";
import { ITEM_TYPES } from "@livrelibre/shared/item";
import { ITEMS_PER_PAGE } from "@livrelibre/shared/pagination";
import { isIn } from "@livrelibre/shared/utils";

import { Card, CardBody, CardFooter, CardTitle } from "@/components/Card";
import { ErrorMessage } from "@/components/ErrorMessage";
import { ItemsTable } from "@/components/ItemsTable";
import { LoadingOverlay } from "@/components/LoadingOverlay";
import { Pagination } from "@/components/Pagination";
import { Title } from "@/components/Title";
import { trpc } from "@/utils/trpc";
import { useDelayedLoading } from "@/utils/useDelayedLoading";
import { useQueryParams } from "@/utils/useQueryParams";

const CARD_STYLES = "max-h-full overflow-hidden flex flex-col relative";

const FIELD_LABELS = {
  type: "Type",
  isbn: "ISBN",
  author: "Auteur·ice",
  title: "Titre",
  publisher: "Maison d'édition",
  distributor: "Distributeur",
  keywords: "Mots-clés",
  datebought: "Date d'achat",
  comments: "Commentaires",
  price: "Prix de vente",
  amount: "Quantité",
  tva: "TVA",
};

const formatRow = ([key, value]: [key: string, value: string]) => {
  const fieldName = isIn(FIELD_LABELS, key) ? FIELD_LABELS[key] : key;
  let fieldValue = value;
  if (key === "type" && isIn(ITEM_TYPES, value)) {
    fieldValue = ITEM_TYPES[value];
  } else if (key === "tva") {
    fieldValue = formatTVA(value) || "";
  }
  return `${fieldName}: ${fieldValue}`;
};

const getQueryLabel = (query: Record<string, string>) => {
  const label = Object.entries(query)
    .filter(([, value]) => value !== "")
    .map(formatRow)
    .join(", ");
  return label;
};

const ToggleStock = () => {
  const { query, push } = useQueryParams();
  const toggleStock = async () => {
    const { inStock, ...rest } = query;
    if (!inStock) {
      rest.inStock = "1";
    }
    await push({ query: rest });
  };
  return (
    <label className="self-end cursor-pointer mr-6 ml-auto">
      <span>En stock</span>
      <input
        type="checkbox"
        className="ml-2"
        onChange={toggleStock}
        defaultChecked={query.inStock == "1"}
      />
    </label>
  );
};

const SearchLoader = ({
  query,
  page,
}: {
  query: Record<string, string>;
  page: number;
}) => {
  const result = trpc.advancedSearch.useQuery(
    { search: query, page },
    {
      placeholderData: keepPreviousData,
    },
  );
  const showLoading = useDelayedLoading(result.isFetching, 500);
  let title = "Recherche avancée";
  let subtitle = "Recherche en cours…";
  let pageCount = 0;
  if (result.isSuccess) {
    const { count } = result.data;
    const queryLabel = getQueryLabel(query);
    pageCount = Math.ceil(count / ITEMS_PER_PAGE);
    if (pageCount > 1) {
      title += ` - Page ${page} sur ${pageCount}`;
    }
    subtitle = `${count} résultat${count > 1 ? "s" : ""} pour ${queryLabel}`;
    if (count === 0) {
      return (
        <Card className={CARD_STYLES}>
          <CardTitle>{title}</CardTitle>
          <ToggleStock />
          <CardBody>Aucun résultat pour &quot;{queryLabel}&quot;</CardBody>
          <p className="mt-2">
            <Link to="/search" className="text-primary-darkest">
              Nouvelle recherche
            </Link>
          </p>
        </Card>
      );
    }
  }
  const Wrapper = showLoading ? LoadingOverlay : React.Fragment;

  return (
    <Card className={CARD_STYLES}>
      <CardTitle>{title}</CardTitle>
      <div className="flex flex-1">
        {subtitle}
        <ToggleStock />
      </div>
      <CardBody>
        {result.isError ? <ErrorMessage /> : null}
        {result.isSuccess ? (
          <Wrapper>
            <ItemsTable items={result.data.items} />
          </Wrapper>
        ) : null}
      </CardBody>
      {pageCount > 1 ? (
        <CardFooter className="flex justify-center pt-6 2xl:pt-8">
          <Pagination count={pageCount} />
        </CardFooter>
      ) : null}
    </Card>
  );
};

const filterNonString = (
  object: Record<string, string | string[] | undefined>,
) => {
  const body: Record<string, string> = {};
  for (const [key, value] of Object.entries(object)) {
    if (typeof value === "string" && key !== "page") {
      body[key] = value;
    }
  }
  return body;
};

const SearchResults = () => {
  const { query } = useQueryParams();
  const page = typeof query.page === "string" ? Number(query.page) : 1;
  return (
    <div className="flex flex-1 flex-col gap-lg">
      <Title>Recherche avancée</Title>
      <SearchLoader query={filterNonString(query)} page={page} />
    </div>
  );
};

export default SearchResults;
