// apps/web-vue/src/pages/quicksearch.vue
<script setup lang="ts">
import { keepPreviousData } from "@tanstack/vue-query";
import { computed } from "vue";

import { ITEMS_PER_PAGE } from "@livrelibre/shared/pagination";

import Card from "@/components/Card.vue";
import CardBody from "@/components/CardBody.vue";
import CardFooter from "@/components/CardFooter.vue";
import CardTitle from "@/components/CardTitle.vue";
import ErrorMessage from "@/components/ErrorMessage.vue";
import ItemsTable from "@/components/ItemsTable.vue";
import LoadingOverlay from "@/components/LoadingOverlay.vue";
import Pagination from "@/components/Pagination.vue";
import Title from "@/components/Title.vue";
import { useTRPCQuery } from "@/utils/query";
import { useDelayedLoading } from "@/utils/useDelayedLoading";
import { useQueryParams } from "@/utils/useQueryParams";

const CARD_STYLES = "max-h-full overflow-hidden flex flex-col relative";

const { query, push } = useQueryParams();

const search = computed(() =>
  typeof query.value.search === "string" ? query.value.search : "",
);
const page = computed(() => {
  const queryPage = query.value.page;
  return typeof queryPage === "string" ? Number(queryPage) : 1;
});
const inStock = computed(() => query.value.inStock === "1");

const toggleStock = async () => {
  const next = inStock.value
    ? { search: search.value }
    : { search: search.value, inStock: 1 };
  await push({ query: next });
};

const result = useTRPCQuery(
  "quicksearch",
  computed(() => ({
    search: search.value,
    page: page.value,
    inStock: inStock.value,
  })),
  { placeholderData: keepPreviousData },
);
const showLoading = useDelayedLoading(
  computed(() => result.isFetching.value),
  500,
);

const pageCount = computed(() =>
  result.data.value ? Math.ceil(result.data.value.count / ITEMS_PER_PAGE) : 0,
);
const cardTitle = computed(() => {
  let title = "Recherche rapide";
  if (pageCount.value > 1) {
    title += ` - Page ${String(page.value)} sur ${String(pageCount.value)}`;
  }
  return title;
});
const subtitle = computed(
  () =>
    `${String(result.data.value?.count ?? 0)} résultat${(result.data.value?.count ?? 0) > 1 ? "s" : ""} pour ${search.value}`,
);
</script>

<template>
  <div class="flex flex-1 flex-col gap-lg">
    <Title>{{ `Recherche de "${search}"` }}</Title>
    <Card
      v-if="result.isSuccess.value && result.data.value?.count === 0"
      :class="CARD_STYLES"
    >
      <CardTitle>{{ cardTitle }}</CardTitle>
      <label class="self-end cursor-pointer mr-6 ml-auto">
        <span>En stock</span>
        <input
          type="checkbox"
          class="ml-2"
          :checked="inStock"
          @change="toggleStock"
        />
      </label>
      <CardBody>Aucun résultat pour "{{ search }}"</CardBody>
    </Card>
    <Card v-else :class="CARD_STYLES">
      <CardTitle>{{ cardTitle }}</CardTitle>
      <div class="flex flex-1">
        <p>{{ result.isSuccess.value ? subtitle : "Recherche en cours…" }}</p>
        <label class="self-end cursor-pointer mr-6 ml-auto">
          <span>En stock</span>
          <input
            type="checkbox"
            class="ml-2"
            :checked="inStock"
            @change="toggleStock"
          />
        </label>
      </div>
      <CardBody>
        <ErrorMessage v-if="result.isError.value" />
        <LoadingOverlay v-if="result.isSuccess.value && showLoading">
          <ItemsTable :items="result.data.value?.items ?? []" />
        </LoadingOverlay>
        <ItemsTable
          v-else-if="result.isSuccess.value"
          :items="result.data.value?.items ?? []"
        />
      </CardBody>
      <CardFooter
        v-if="pageCount > 1"
        class="flex justify-center pt-6 2xl:pt-8"
      >
        <Pagination :count="pageCount" />
      </CardFooter>
    </Card>
  </div>
</template>

// apps/web/src/pages/quicksearch.tsx
import * as React from "react";
import { keepPreviousData } from "@tanstack/react-query";

import { ITEMS_PER_PAGE } from "@livrelibre/shared/pagination";

import { Card, CardBody, CardFooter, CardTitle } from "@/components/Card";
import { ItemsTable } from "@/components/ItemsTable";
import { LoadingOverlay } from "@/components/LoadingOverlay";
import { Pagination } from "@/components/Pagination";
import { Title } from "@/components/Title";
import { trpc } from "@/utils/trpc";
import { useDelayedLoading } from "@/utils/useDelayedLoading";
import { useQueryParams } from "@/utils/useQueryParams";

const CARD_STYLES = "max-h-full overflow-hidden flex flex-col relative";

const useQuickSearchParams = () => {
  const { query } = useQueryParams();
  const search = typeof query.search === "string" ? query.search : "";
  const page = typeof query.page === "string" ? Number(query.page) : 1;
  const inStock = typeof query.inStock === "string";
  return { search, page, inStock };
};

const ToggleStock = () => {
  const { push } = useQueryParams();
  const { search, inStock } = useQuickSearchParams();
  const toggleStock = async () => {
    const query = inStock ? { search } : { search, inStock: 1 };
    await push({ query });
  };
  return (
    <label className="self-end cursor-pointer mr-6 ml-auto">
      <span>En stock</span>
      <input
        type="checkbox"
        className="ml-2"
        onChange={toggleStock}
        defaultChecked={inStock}
      />
    </label>
  );
};

const SearchLoader = ({
  page,
  search,
  inStock,
}: {
  page: number;
  search: string;
  inStock: boolean;
}) => {
  const result = trpc.quicksearch.useQuery(
    { search, page, inStock },
    {
      placeholderData: keepPreviousData,
    },
  );
  const showLoading = useDelayedLoading(result.isFetching, 500);
  let title = "Recherche rapide";
  let subtitle = "Recherche en cours…";
  let pageCount = 0;
  if (result.isSuccess) {
    const { count } = result.data;
    pageCount = Math.ceil(count / ITEMS_PER_PAGE);
    if (pageCount > 1) {
      title += ` - Page ${page} sur ${pageCount}`;
    }
    subtitle = `${count} résultat${count > 1 ? "s" : ""} pour ${search}`;
    if (count === 0) {
      return (
        <Card className={CARD_STYLES}>
          <CardTitle>{title}</CardTitle>
          <ToggleStock />
          <CardBody>Aucun résultat pour &quot;{search}&quot;</CardBody>
        </Card>
      );
    }
  }
  const Wrapper = showLoading ? LoadingOverlay : React.Fragment;

  return (
    <Card className={CARD_STYLES}>
      <CardTitle>{title}</CardTitle>
      <div className="flex flex-1">
        {subtitle}
        <ToggleStock />
      </div>
      <CardBody>
        {result.isSuccess ? (
          <Wrapper>
            <ItemsTable items={result.data.items} />
          </Wrapper>
        ) : null}
      </CardBody>
      {pageCount > 1 ? (
        <CardFooter className="flex justify-center pt-6 2xl:pt-8">
          <Pagination count={pageCount} />
        </CardFooter>
      ) : null}
    </Card>
  );
};

const QuickSearchPage = (): React.ReactElement => {
  const { search, page, inStock } = useQuickSearchParams();
  const title = `Recherche de "${search}"`;
  return (
    <div className="flex flex-1 flex-col gap-lg">
      <Title>{title}</Title>
      {search ? (
        <SearchLoader search={search} page={page} inStock={inStock} />
      ) : null}
    </div>
  );
};

export default QuickSearchPage;
